// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: notification.proto

package notification

import (
	common "github.com/Keneke-Einar/delivertrack/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED               NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_DELIVERY_CREATED          NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_DELIVERY_PICKED_UP        NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_DELIVERY_IN_TRANSIT       NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_DELIVERY_OUT_FOR_DELIVERY NotificationType = 4
	NotificationType_NOTIFICATION_TYPE_DELIVERY_DELIVERED        NotificationType = 5
	NotificationType_NOTIFICATION_TYPE_DELIVERY_FAILED           NotificationType = 6
	NotificationType_NOTIFICATION_TYPE_DELIVERY_DELAYED          NotificationType = 7
	NotificationType_NOTIFICATION_TYPE_DELIVERY_CANCELLED        NotificationType = 8
	NotificationType_NOTIFICATION_TYPE_DRIVER_ASSIGNED           NotificationType = 9
	NotificationType_NOTIFICATION_TYPE_LOCATION_UPDATE           NotificationType = 10
	NotificationType_NOTIFICATION_TYPE_SYSTEM_ALERT              NotificationType = 11
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0:  "NOTIFICATION_TYPE_UNSPECIFIED",
		1:  "NOTIFICATION_TYPE_DELIVERY_CREATED",
		2:  "NOTIFICATION_TYPE_DELIVERY_PICKED_UP",
		3:  "NOTIFICATION_TYPE_DELIVERY_IN_TRANSIT",
		4:  "NOTIFICATION_TYPE_DELIVERY_OUT_FOR_DELIVERY",
		5:  "NOTIFICATION_TYPE_DELIVERY_DELIVERED",
		6:  "NOTIFICATION_TYPE_DELIVERY_FAILED",
		7:  "NOTIFICATION_TYPE_DELIVERY_DELAYED",
		8:  "NOTIFICATION_TYPE_DELIVERY_CANCELLED",
		9:  "NOTIFICATION_TYPE_DRIVER_ASSIGNED",
		10: "NOTIFICATION_TYPE_LOCATION_UPDATE",
		11: "NOTIFICATION_TYPE_SYSTEM_ALERT",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED":               0,
		"NOTIFICATION_TYPE_DELIVERY_CREATED":          1,
		"NOTIFICATION_TYPE_DELIVERY_PICKED_UP":        2,
		"NOTIFICATION_TYPE_DELIVERY_IN_TRANSIT":       3,
		"NOTIFICATION_TYPE_DELIVERY_OUT_FOR_DELIVERY": 4,
		"NOTIFICATION_TYPE_DELIVERY_DELIVERED":        5,
		"NOTIFICATION_TYPE_DELIVERY_FAILED":           6,
		"NOTIFICATION_TYPE_DELIVERY_DELAYED":          7,
		"NOTIFICATION_TYPE_DELIVERY_CANCELLED":        8,
		"NOTIFICATION_TYPE_DRIVER_ASSIGNED":           9,
		"NOTIFICATION_TYPE_LOCATION_UPDATE":           10,
		"NOTIFICATION_TYPE_SYSTEM_ALERT":              11,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

type NotificationChannel int32

const (
	NotificationChannel_CHANNEL_UNSPECIFIED NotificationChannel = 0
	NotificationChannel_CHANNEL_EMAIL       NotificationChannel = 1
	NotificationChannel_CHANNEL_SMS         NotificationChannel = 2
	NotificationChannel_CHANNEL_PUSH        NotificationChannel = 3
	NotificationChannel_CHANNEL_IN_APP      NotificationChannel = 4
	NotificationChannel_CHANNEL_WEBHOOK     NotificationChannel = 5
)

// Enum value maps for NotificationChannel.
var (
	NotificationChannel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_EMAIL",
		2: "CHANNEL_SMS",
		3: "CHANNEL_PUSH",
		4: "CHANNEL_IN_APP",
		5: "CHANNEL_WEBHOOK",
	}
	NotificationChannel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_EMAIL":       1,
		"CHANNEL_SMS":         2,
		"CHANNEL_PUSH":        3,
		"CHANNEL_IN_APP":      4,
		"CHANNEL_WEBHOOK":     5,
	}
)

func (x NotificationChannel) Enum() *NotificationChannel {
	p := new(NotificationChannel)
	*p = x
	return p
}

func (x NotificationChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[1].Descriptor()
}

func (NotificationChannel) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[1]
}

func (x NotificationChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationChannel.Descriptor instead.
func (NotificationChannel) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

type NotificationStatus int32

const (
	NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED NotificationStatus = 0
	NotificationStatus_NOTIFICATION_STATUS_PENDING     NotificationStatus = 1
	NotificationStatus_NOTIFICATION_STATUS_SENT        NotificationStatus = 2
	NotificationStatus_NOTIFICATION_STATUS_DELIVERED   NotificationStatus = 3
	NotificationStatus_NOTIFICATION_STATUS_FAILED      NotificationStatus = 4
	NotificationStatus_NOTIFICATION_STATUS_BOUNCED     NotificationStatus = 5
)

// Enum value maps for NotificationStatus.
var (
	NotificationStatus_name = map[int32]string{
		0: "NOTIFICATION_STATUS_UNSPECIFIED",
		1: "NOTIFICATION_STATUS_PENDING",
		2: "NOTIFICATION_STATUS_SENT",
		3: "NOTIFICATION_STATUS_DELIVERED",
		4: "NOTIFICATION_STATUS_FAILED",
		5: "NOTIFICATION_STATUS_BOUNCED",
	}
	NotificationStatus_value = map[string]int32{
		"NOTIFICATION_STATUS_UNSPECIFIED": 0,
		"NOTIFICATION_STATUS_PENDING":     1,
		"NOTIFICATION_STATUS_SENT":        2,
		"NOTIFICATION_STATUS_DELIVERED":   3,
		"NOTIFICATION_STATUS_FAILED":      4,
		"NOTIFICATION_STATUS_BOUNCED":     5,
	}
)

func (x NotificationStatus) Enum() *NotificationStatus {
	p := new(NotificationStatus)
	*p = x
	return p
}

func (x NotificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[2].Descriptor()
}

func (NotificationStatus) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[2]
}

func (x NotificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationStatus.Descriptor instead.
func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

type NotificationPriority int32

const (
	NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED NotificationPriority = 0
	NotificationPriority_NOTIFICATION_PRIORITY_LOW         NotificationPriority = 1
	NotificationPriority_NOTIFICATION_PRIORITY_NORMAL      NotificationPriority = 2
	NotificationPriority_NOTIFICATION_PRIORITY_HIGH        NotificationPriority = 3
	NotificationPriority_NOTIFICATION_PRIORITY_URGENT      NotificationPriority = 4
)

// Enum value maps for NotificationPriority.
var (
	NotificationPriority_name = map[int32]string{
		0: "NOTIFICATION_PRIORITY_UNSPECIFIED",
		1: "NOTIFICATION_PRIORITY_LOW",
		2: "NOTIFICATION_PRIORITY_NORMAL",
		3: "NOTIFICATION_PRIORITY_HIGH",
		4: "NOTIFICATION_PRIORITY_URGENT",
	}
	NotificationPriority_value = map[string]int32{
		"NOTIFICATION_PRIORITY_UNSPECIFIED": 0,
		"NOTIFICATION_PRIORITY_LOW":         1,
		"NOTIFICATION_PRIORITY_NORMAL":      2,
		"NOTIFICATION_PRIORITY_HIGH":        3,
		"NOTIFICATION_PRIORITY_URGENT":      4,
	}
)

func (x NotificationPriority) Enum() *NotificationPriority {
	p := new(NotificationPriority)
	*p = x
	return p
}

func (x NotificationPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[3].Descriptor()
}

func (NotificationPriority) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[3]
}

func (x NotificationPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationPriority.Descriptor instead.
func (NotificationPriority) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientId   string                 `protobuf:"bytes,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=delivertrack.notification.NotificationType" json:"type,omitempty"`
	Channel       NotificationChannel    `protobuf:"varint,3,opt,name=channel,proto3,enum=delivertrack.notification.NotificationChannel" json:"channel,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Data          map[string]string      `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority      NotificationPriority   `protobuf:"varint,7,opt,name=priority,proto3,enum=delivertrack.notification.NotificationPriority" json:"priority,omitempty"`
	ScheduleAt    int64                  `protobuf:"varint,8,opt,name=schedule_at,json=scheduleAt,proto3" json:"schedule_at,omitempty"` // Unix timestamp, 0 for immediate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendNotificationRequest) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *SendNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *SendNotificationRequest) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_CHANNEL_UNSPECIFIED
}

func (x *SendNotificationRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendNotificationRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendNotificationRequest) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *SendNotificationRequest) GetScheduleAt() int64 {
	if x != nil {
		return x.ScheduleAt
	}
	return 0
}

type SendNotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Status         NotificationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=delivertrack.notification.NotificationStatus" json:"status,omitempty"`
	SentAt         int64                  `protobuf:"varint,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *SendNotificationResponse) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *SendNotificationResponse) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

type SendBulkNotificationsRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Notifications []*SendNotificationRequest `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkNotificationsRequest) Reset() {
	*x = SendBulkNotificationsRequest{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkNotificationsRequest) ProtoMessage() {}

func (x *SendBulkNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkNotificationsRequest.ProtoReflect.Descriptor instead.
func (*SendBulkNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendBulkNotificationsRequest) GetNotifications() []*SendNotificationRequest {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type SendBulkNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	Results       []*NotificationResult  `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkNotificationsResponse) Reset() {
	*x = SendBulkNotificationsResponse{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkNotificationsResponse) ProtoMessage() {}

func (x *SendBulkNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkNotificationsResponse.ProtoReflect.Descriptor instead.
func (*SendBulkNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *SendBulkNotificationsResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *SendBulkNotificationsResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *SendBulkNotificationsResponse) GetResults() []*NotificationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type NotificationResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationResult) Reset() {
	*x = NotificationResult{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResult) ProtoMessage() {}

func (x *NotificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResult.ProtoReflect.Descriptor instead.
func (*NotificationResult) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *NotificationResult) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NotificationResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetNotificationHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientId   string                 `protobuf:"bytes,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=delivertrack.notification.NotificationType" json:"type,omitempty"`
	TimeRange     *common.TimeRange      `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	UnreadOnly    bool                   `protobuf:"varint,5,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationHistoryRequest) Reset() {
	*x = GetNotificationHistoryRequest{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationHistoryRequest) ProtoMessage() {}

func (x *GetNotificationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *GetNotificationHistoryRequest) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *GetNotificationHistoryRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *GetNotificationHistoryRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *GetNotificationHistoryRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetNotificationHistoryRequest) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

type GetNotificationHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationHistoryResponse) Reset() {
	*x = GetNotificationHistoryResponse{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationHistoryResponse) ProtoMessage() {}

func (x *GetNotificationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *GetNotificationHistoryResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *GetNotificationHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetNotificationHistoryResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type Notification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	RecipientId    string                 `protobuf:"bytes,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Type           NotificationType       `protobuf:"varint,3,opt,name=type,proto3,enum=delivertrack.notification.NotificationType" json:"type,omitempty"`
	Channel        NotificationChannel    `protobuf:"varint,4,opt,name=channel,proto3,enum=delivertrack.notification.NotificationChannel" json:"channel,omitempty"`
	Subject        string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Message        string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Data           map[string]string      `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status         NotificationStatus     `protobuf:"varint,8,opt,name=status,proto3,enum=delivertrack.notification.NotificationStatus" json:"status,omitempty"`
	Priority       NotificationPriority   `protobuf:"varint,9,opt,name=priority,proto3,enum=delivertrack.notification.NotificationPriority" json:"priority,omitempty"`
	Read           bool                   `protobuf:"varint,10,opt,name=read,proto3" json:"read,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SentAt         int64                  `protobuf:"varint,12,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ReadAt         int64                  `protobuf:"varint,13,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{7}
}

func (x *Notification) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *Notification) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *Notification) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_CHANNEL_UNSPECIFIED
}

func (x *Notification) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Notification) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *Notification) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Notification) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *Notification) GetReadAt() int64 {
	if x != nil {
		return x.ReadAt
	}
	return 0
}

type UpdatePreferencesRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	UserId        string                   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences   *NotificationPreferences `protobuf:"bytes,2,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdatePreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesResponse) Reset() {
	*x = UpdatePreferencesResponse{}
	mi := &file_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesResponse) ProtoMessage() {}

func (x *UpdatePreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePreferencesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePreferencesResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{10}
}

func (x *GetPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPreferencesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesResponse) Reset() {
	*x = GetPreferencesResponse{}
	mi := &file_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesResponse) ProtoMessage() {}

func (x *GetPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{11}
}

func (x *GetPreferencesResponse) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type NotificationPreferences struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EmailEnabled      bool                   `protobuf:"varint,1,opt,name=email_enabled,json=emailEnabled,proto3" json:"email_enabled,omitempty"`
	SmsEnabled        bool                   `protobuf:"varint,2,opt,name=sms_enabled,json=smsEnabled,proto3" json:"sms_enabled,omitempty"`
	PushEnabled       bool                   `protobuf:"varint,3,opt,name=push_enabled,json=pushEnabled,proto3" json:"push_enabled,omitempty"`
	InAppEnabled      bool                   `protobuf:"varint,4,opt,name=in_app_enabled,json=inAppEnabled,proto3" json:"in_app_enabled,omitempty"`
	NotificationTypes map[string]bool        `protobuf:"bytes,5,rep,name=notification_types,json=notificationTypes,proto3" json:"notification_types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // notification type -> enabled
	QuietHours        *QuietHours            `protobuf:"bytes,6,opt,name=quiet_hours,json=quietHours,proto3" json:"quiet_hours,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotificationPreferences) Reset() {
	*x = NotificationPreferences{}
	mi := &file_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreferences) ProtoMessage() {}

func (x *NotificationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreferences.ProtoReflect.Descriptor instead.
func (*NotificationPreferences) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{12}
}

func (x *NotificationPreferences) GetEmailEnabled() bool {
	if x != nil {
		return x.EmailEnabled
	}
	return false
}

func (x *NotificationPreferences) GetSmsEnabled() bool {
	if x != nil {
		return x.SmsEnabled
	}
	return false
}

func (x *NotificationPreferences) GetPushEnabled() bool {
	if x != nil {
		return x.PushEnabled
	}
	return false
}

func (x *NotificationPreferences) GetInAppEnabled() bool {
	if x != nil {
		return x.InAppEnabled
	}
	return false
}

func (x *NotificationPreferences) GetNotificationTypes() map[string]bool {
	if x != nil {
		return x.NotificationTypes
	}
	return nil
}

func (x *NotificationPreferences) GetQuietHours() *QuietHours {
	if x != nil {
		return x.QuietHours
	}
	return nil
}

type QuietHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	StartHour     int32                  `protobuf:"varint,2,opt,name=start_hour,json=startHour,proto3" json:"start_hour,omitempty"` // 0-23
	EndHour       int32                  `protobuf:"varint,3,opt,name=end_hour,json=endHour,proto3" json:"end_hour,omitempty"`       // 0-23
	Timezone      string                 `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuietHours) Reset() {
	*x = QuietHours{}
	mi := &file_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuietHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuietHours) ProtoMessage() {}

func (x *QuietHours) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuietHours.ProtoReflect.Descriptor instead.
func (*QuietHours) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{13}
}

func (x *QuietHours) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *QuietHours) GetStartHour() int32 {
	if x != nil {
		return x.StartHour
	}
	return 0
}

func (x *QuietHours) GetEndHour() int32 {
	if x != nil {
		return x.EndHour
	}
	return 0
}

func (x *QuietHours) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Types         []NotificationType     `protobuf:"varint,2,rep,packed,name=types,proto3,enum=delivertrack.notification.NotificationType" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscribeRequest) GetTypes() []NotificationType {
	if x != nil {
		return x.Types
	}
	return nil
}

type MarkAsReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_notification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{15}
}

func (x *MarkAsReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *MarkAsReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MarkAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReadAt        int64                  `protobuf:"varint,2,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadResponse) Reset() {
	*x = MarkAsReadResponse{}
	mi := &file_notification_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadResponse) ProtoMessage() {}

func (x *MarkAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAsReadResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{16}
}

func (x *MarkAsReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MarkAsReadResponse) GetReadAt() int64 {
	if x != nil {
		return x.ReadAt
	}
	return 0
}

type SendDeliveryUpdateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId        string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	CustomerId        string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	TrackingNumber    string                 `protobuf:"bytes,3,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message           string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Location          *common.Location       `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	EstimatedDelivery int64                  `protobuf:"varint,7,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendDeliveryUpdateRequest) Reset() {
	*x = SendDeliveryUpdateRequest{}
	mi := &file_notification_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDeliveryUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDeliveryUpdateRequest) ProtoMessage() {}

func (x *SendDeliveryUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDeliveryUpdateRequest.ProtoReflect.Descriptor instead.
func (*SendDeliveryUpdateRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{17}
}

func (x *SendDeliveryUpdateRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *SendDeliveryUpdateRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SendDeliveryUpdateRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *SendDeliveryUpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendDeliveryUpdateRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendDeliveryUpdateRequest) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *SendDeliveryUpdateRequest) GetEstimatedDelivery() int64 {
	if x != nil {
		return x.EstimatedDelivery
	}
	return 0
}

type SendDeliveryUpdateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	SentAt         int64                  `protobuf:"varint,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendDeliveryUpdateResponse) Reset() {
	*x = SendDeliveryUpdateResponse{}
	mi := &file_notification_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDeliveryUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDeliveryUpdateResponse) ProtoMessage() {}

func (x *SendDeliveryUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDeliveryUpdateResponse.ProtoReflect.Descriptor instead.
func (*SendDeliveryUpdateResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{18}
}

func (x *SendDeliveryUpdateResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *SendDeliveryUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendDeliveryUpdateResponse) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\x19delivertrack.notification\x1a\fcommon.proto\"\xf4\x03\n" +
	"\x17SendNotificationRequest\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\tR\vrecipientId\x12?\n" +
	"\x04type\x18\x02 \x01(\x0e2+.delivertrack.notification.NotificationTypeR\x04type\x12H\n" +
	"\achannel\x18\x03 \x01(\x0e2..delivertrack.notification.NotificationChannelR\achannel\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12P\n" +
	"\x04data\x18\x06 \x03(\v2<.delivertrack.notification.SendNotificationRequest.DataEntryR\x04data\x12K\n" +
	"\bpriority\x18\a \x01(\x0e2/.delivertrack.notification.NotificationPriorityR\bpriority\x12\x1f\n" +
	"\vschedule_at\x18\b \x01(\x03R\n" +
	"scheduleAt\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x01\n" +
	"\x18SendNotificationResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12E\n" +
	"\x06status\x18\x02 \x01(\x0e2-.delivertrack.notification.NotificationStatusR\x06status\x12\x17\n" +
	"\asent_at\x18\x03 \x01(\x03R\x06sentAt\"x\n" +
	"\x1cSendBulkNotificationsRequest\x12X\n" +
	"\rnotifications\x18\x01 \x03(\v22.delivertrack.notification.SendNotificationRequestR\rnotifications\"\xb0\x01\n" +
	"\x1dSendBulkNotificationsResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x12G\n" +
	"\aresults\x18\x03 \x03(\v2-.delivertrack.notification.NotificationResultR\aresults\"|\n" +
	"\x12NotificationResult\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xa4\x02\n" +
	"\x1dGetNotificationHistoryRequest\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\tR\vrecipientId\x12?\n" +
	"\x04type\x18\x02 \x01(\x0e2+.delivertrack.notification.NotificationTypeR\x04type\x12=\n" +
	"\n" +
	"time_range\x18\x03 \x01(\v2\x1e.delivertrack.common.TimeRangeR\ttimeRange\x12?\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1f.delivertrack.common.PaginationR\n" +
	"pagination\x12\x1f\n" +
	"\vunread_only\x18\x05 \x01(\bR\n" +
	"unreadOnly\"\xb3\x01\n" +
	"\x1eGetNotificationHistoryResponse\x12M\n" +
	"\rnotifications\x18\x01 \x03(\v2'.delivertrack.notification.NotificationR\rnotifications\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\funread_count\x18\x03 \x01(\x05R\vunreadCount\"\x92\x05\n" +
	"\fNotification\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\tR\vrecipientId\x12?\n" +
	"\x04type\x18\x03 \x01(\x0e2+.delivertrack.notification.NotificationTypeR\x04type\x12H\n" +
	"\achannel\x18\x04 \x01(\x0e2..delivertrack.notification.NotificationChannelR\achannel\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12E\n" +
	"\x04data\x18\a \x03(\v21.delivertrack.notification.Notification.DataEntryR\x04data\x12E\n" +
	"\x06status\x18\b \x01(\x0e2-.delivertrack.notification.NotificationStatusR\x06status\x12K\n" +
	"\bpriority\x18\t \x01(\x0e2/.delivertrack.notification.NotificationPriorityR\bpriority\x12\x12\n" +
	"\x04read\x18\n" +
	" \x01(\bR\x04read\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x17\n" +
	"\asent_at\x18\f \x01(\x03R\x06sentAt\x12\x17\n" +
	"\aread_at\x18\r \x01(\x03R\x06readAt\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\x18UpdatePreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12T\n" +
	"\vpreferences\x18\x02 \x01(\v22.delivertrack.notification.NotificationPreferencesR\vpreferences\"T\n" +
	"\x19UpdatePreferencesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\x03R\tupdatedAt\"0\n" +
	"\x15GetPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"n\n" +
	"\x16GetPreferencesResponse\x12T\n" +
	"\vpreferences\x18\x01 \x01(\v22.delivertrack.notification.NotificationPreferencesR\vpreferences\"\xb0\x03\n" +
	"\x17NotificationPreferences\x12#\n" +
	"\remail_enabled\x18\x01 \x01(\bR\femailEnabled\x12\x1f\n" +
	"\vsms_enabled\x18\x02 \x01(\bR\n" +
	"smsEnabled\x12!\n" +
	"\fpush_enabled\x18\x03 \x01(\bR\vpushEnabled\x12$\n" +
	"\x0ein_app_enabled\x18\x04 \x01(\bR\finAppEnabled\x12x\n" +
	"\x12notification_types\x18\x05 \x03(\v2I.delivertrack.notification.NotificationPreferences.NotificationTypesEntryR\x11notificationTypes\x12F\n" +
	"\vquiet_hours\x18\x06 \x01(\v2%.delivertrack.notification.QuietHoursR\n" +
	"quietHours\x1aD\n" +
	"\x16NotificationTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"|\n" +
	"\n" +
	"QuietHours\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"start_hour\x18\x02 \x01(\x05R\tstartHour\x12\x19\n" +
	"\bend_hour\x18\x03 \x01(\x05R\aendHour\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\"n\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12A\n" +
	"\x05types\x18\x02 \x03(\x0e2+.delivertrack.notification.NotificationTypeR\x05types\"U\n" +
	"\x11MarkAsReadRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"G\n" +
	"\x12MarkAsReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aread_at\x18\x02 \x01(\x03R\x06readAt\"\xa2\x02\n" +
	"\x19SendDeliveryUpdateRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12'\n" +
	"\x0ftracking_number\x18\x03 \x01(\tR\x0etrackingNumber\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x129\n" +
	"\blocation\x18\x06 \x01(\v2\x1d.delivertrack.common.LocationR\blocation\x12-\n" +
	"\x12estimated_delivery\x18\a \x01(\x03R\x11estimatedDelivery\"x\n" +
	"\x1aSendDeliveryUpdateResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x17\n" +
	"\asent_at\x18\x03 \x01(\x03R\x06sentAt*\xf8\x03\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"NOTIFICATION_TYPE_DELIVERY_CREATED\x10\x01\x12(\n" +
	"$NOTIFICATION_TYPE_DELIVERY_PICKED_UP\x10\x02\x12)\n" +
	"%NOTIFICATION_TYPE_DELIVERY_IN_TRANSIT\x10\x03\x12/\n" +
	"+NOTIFICATION_TYPE_DELIVERY_OUT_FOR_DELIVERY\x10\x04\x12(\n" +
	"$NOTIFICATION_TYPE_DELIVERY_DELIVERED\x10\x05\x12%\n" +
	"!NOTIFICATION_TYPE_DELIVERY_FAILED\x10\x06\x12&\n" +
	"\"NOTIFICATION_TYPE_DELIVERY_DELAYED\x10\a\x12(\n" +
	"$NOTIFICATION_TYPE_DELIVERY_CANCELLED\x10\b\x12%\n" +
	"!NOTIFICATION_TYPE_DRIVER_ASSIGNED\x10\t\x12%\n" +
	"!NOTIFICATION_TYPE_LOCATION_UPDATE\x10\n" +
	"\x12\"\n" +
	"\x1eNOTIFICATION_TYPE_SYSTEM_ALERT\x10\v*\x8d\x01\n" +
	"\x13NotificationChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCHANNEL_EMAIL\x10\x01\x12\x0f\n" +
	"\vCHANNEL_SMS\x10\x02\x12\x10\n" +
	"\fCHANNEL_PUSH\x10\x03\x12\x12\n" +
	"\x0eCHANNEL_IN_APP\x10\x04\x12\x13\n" +
	"\x0fCHANNEL_WEBHOOK\x10\x05*\xdc\x01\n" +
	"\x12NotificationStatus\x12#\n" +
	"\x1fNOTIFICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bNOTIFICATION_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_STATUS_SENT\x10\x02\x12!\n" +
	"\x1dNOTIFICATION_STATUS_DELIVERED\x10\x03\x12\x1e\n" +
	"\x1aNOTIFICATION_STATUS_FAILED\x10\x04\x12\x1f\n" +
	"\x1bNOTIFICATION_STATUS_BOUNCED\x10\x05*\xc0\x01\n" +
	"\x14NotificationPriority\x12%\n" +
	"!NOTIFICATION_PRIORITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19NOTIFICATION_PRIORITY_LOW\x10\x01\x12 \n" +
	"\x1cNOTIFICATION_PRIORITY_NORMAL\x10\x02\x12\x1e\n" +
	"\x1aNOTIFICATION_PRIORITY_HIGH\x10\x03\x12 \n" +
	"\x1cNOTIFICATION_PRIORITY_URGENT\x10\x042\xfa\a\n" +
	"\x13NotificationService\x12{\n" +
	"\x10SendNotification\x122.delivertrack.notification.SendNotificationRequest\x1a3.delivertrack.notification.SendNotificationResponse\x12\x8a\x01\n" +
	"\x15SendBulkNotifications\x127.delivertrack.notification.SendBulkNotificationsRequest\x1a8.delivertrack.notification.SendBulkNotificationsResponse\x12\x8d\x01\n" +
	"\x16GetNotificationHistory\x128.delivertrack.notification.GetNotificationHistoryRequest\x1a9.delivertrack.notification.GetNotificationHistoryResponse\x12~\n" +
	"\x11UpdatePreferences\x123.delivertrack.notification.UpdatePreferencesRequest\x1a4.delivertrack.notification.UpdatePreferencesResponse\x12u\n" +
	"\x0eGetPreferences\x120.delivertrack.notification.GetPreferencesRequest\x1a1.delivertrack.notification.GetPreferencesResponse\x12c\n" +
	"\tSubscribe\x12+.delivertrack.notification.SubscribeRequest\x1a'.delivertrack.notification.Notification0\x01\x12i\n" +
	"\n" +
	"MarkAsRead\x12,.delivertrack.notification.MarkAsReadRequest\x1a-.delivertrack.notification.MarkAsReadResponse\x12\x81\x01\n" +
	"\x12SendDeliveryUpdate\x124.delivertrack.notification.SendDeliveryUpdateRequest\x1a5.delivertrack.notification.SendDeliveryUpdateResponseB9Z7github.com/Keneke-Einar/delivertrack/proto/notificationb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_notification_proto_goTypes = []any{
	(NotificationType)(0),                  // 0: delivertrack.notification.NotificationType
	(NotificationChannel)(0),               // 1: delivertrack.notification.NotificationChannel
	(NotificationStatus)(0),                // 2: delivertrack.notification.NotificationStatus
	(NotificationPriority)(0),              // 3: delivertrack.notification.NotificationPriority
	(*SendNotificationRequest)(nil),        // 4: delivertrack.notification.SendNotificationRequest
	(*SendNotificationResponse)(nil),       // 5: delivertrack.notification.SendNotificationResponse
	(*SendBulkNotificationsRequest)(nil),   // 6: delivertrack.notification.SendBulkNotificationsRequest
	(*SendBulkNotificationsResponse)(nil),  // 7: delivertrack.notification.SendBulkNotificationsResponse
	(*NotificationResult)(nil),             // 8: delivertrack.notification.NotificationResult
	(*GetNotificationHistoryRequest)(nil),  // 9: delivertrack.notification.GetNotificationHistoryRequest
	(*GetNotificationHistoryResponse)(nil), // 10: delivertrack.notification.GetNotificationHistoryResponse
	(*Notification)(nil),                   // 11: delivertrack.notification.Notification
	(*UpdatePreferencesRequest)(nil),       // 12: delivertrack.notification.UpdatePreferencesRequest
	(*UpdatePreferencesResponse)(nil),      // 13: delivertrack.notification.UpdatePreferencesResponse
	(*GetPreferencesRequest)(nil),          // 14: delivertrack.notification.GetPreferencesRequest
	(*GetPreferencesResponse)(nil),         // 15: delivertrack.notification.GetPreferencesResponse
	(*NotificationPreferences)(nil),        // 16: delivertrack.notification.NotificationPreferences
	(*QuietHours)(nil),                     // 17: delivertrack.notification.QuietHours
	(*SubscribeRequest)(nil),               // 18: delivertrack.notification.SubscribeRequest
	(*MarkAsReadRequest)(nil),              // 19: delivertrack.notification.MarkAsReadRequest
	(*MarkAsReadResponse)(nil),             // 20: delivertrack.notification.MarkAsReadResponse
	(*SendDeliveryUpdateRequest)(nil),      // 21: delivertrack.notification.SendDeliveryUpdateRequest
	(*SendDeliveryUpdateResponse)(nil),     // 22: delivertrack.notification.SendDeliveryUpdateResponse
	nil,                                    // 23: delivertrack.notification.SendNotificationRequest.DataEntry
	nil,                                    // 24: delivertrack.notification.Notification.DataEntry
	nil,                                    // 25: delivertrack.notification.NotificationPreferences.NotificationTypesEntry
	(*common.TimeRange)(nil),               // 26: delivertrack.common.TimeRange
	(*common.Pagination)(nil),              // 27: delivertrack.common.Pagination
	(*common.Location)(nil),                // 28: delivertrack.common.Location
}
var file_notification_proto_depIdxs = []int32{
	0,  // 0: delivertrack.notification.SendNotificationRequest.type:type_name -> delivertrack.notification.NotificationType
	1,  // 1: delivertrack.notification.SendNotificationRequest.channel:type_name -> delivertrack.notification.NotificationChannel
	23, // 2: delivertrack.notification.SendNotificationRequest.data:type_name -> delivertrack.notification.SendNotificationRequest.DataEntry
	3,  // 3: delivertrack.notification.SendNotificationRequest.priority:type_name -> delivertrack.notification.NotificationPriority
	2,  // 4: delivertrack.notification.SendNotificationResponse.status:type_name -> delivertrack.notification.NotificationStatus
	4,  // 5: delivertrack.notification.SendBulkNotificationsRequest.notifications:type_name -> delivertrack.notification.SendNotificationRequest
	8,  // 6: delivertrack.notification.SendBulkNotificationsResponse.results:type_name -> delivertrack.notification.NotificationResult
	0,  // 7: delivertrack.notification.GetNotificationHistoryRequest.type:type_name -> delivertrack.notification.NotificationType
	26, // 8: delivertrack.notification.GetNotificationHistoryRequest.time_range:type_name -> delivertrack.common.TimeRange
	27, // 9: delivertrack.notification.GetNotificationHistoryRequest.pagination:type_name -> delivertrack.common.Pagination
	11, // 10: delivertrack.notification.GetNotificationHistoryResponse.notifications:type_name -> delivertrack.notification.Notification
	0,  // 11: delivertrack.notification.Notification.type:type_name -> delivertrack.notification.NotificationType
	1,  // 12: delivertrack.notification.Notification.channel:type_name -> delivertrack.notification.NotificationChannel
	24, // 13: delivertrack.notification.Notification.data:type_name -> delivertrack.notification.Notification.DataEntry
	2,  // 14: delivertrack.notification.Notification.status:type_name -> delivertrack.notification.NotificationStatus
	3,  // 15: delivertrack.notification.Notification.priority:type_name -> delivertrack.notification.NotificationPriority
	16, // 16: delivertrack.notification.UpdatePreferencesRequest.preferences:type_name -> delivertrack.notification.NotificationPreferences
	16, // 17: delivertrack.notification.GetPreferencesResponse.preferences:type_name -> delivertrack.notification.NotificationPreferences
	25, // 18: delivertrack.notification.NotificationPreferences.notification_types:type_name -> delivertrack.notification.NotificationPreferences.NotificationTypesEntry
	17, // 19: delivertrack.notification.NotificationPreferences.quiet_hours:type_name -> delivertrack.notification.QuietHours
	0,  // 20: delivertrack.notification.SubscribeRequest.types:type_name -> delivertrack.notification.NotificationType
	28, // 21: delivertrack.notification.SendDeliveryUpdateRequest.location:type_name -> delivertrack.common.Location
	4,  // 22: delivertrack.notification.NotificationService.SendNotification:input_type -> delivertrack.notification.SendNotificationRequest
	6,  // 23: delivertrack.notification.NotificationService.SendBulkNotifications:input_type -> delivertrack.notification.SendBulkNotificationsRequest
	9,  // 24: delivertrack.notification.NotificationService.GetNotificationHistory:input_type -> delivertrack.notification.GetNotificationHistoryRequest
	12, // 25: delivertrack.notification.NotificationService.UpdatePreferences:input_type -> delivertrack.notification.UpdatePreferencesRequest
	14, // 26: delivertrack.notification.NotificationService.GetPreferences:input_type -> delivertrack.notification.GetPreferencesRequest
	18, // 27: delivertrack.notification.NotificationService.Subscribe:input_type -> delivertrack.notification.SubscribeRequest
	19, // 28: delivertrack.notification.NotificationService.MarkAsRead:input_type -> delivertrack.notification.MarkAsReadRequest
	21, // 29: delivertrack.notification.NotificationService.SendDeliveryUpdate:input_type -> delivertrack.notification.SendDeliveryUpdateRequest
	5,  // 30: delivertrack.notification.NotificationService.SendNotification:output_type -> delivertrack.notification.SendNotificationResponse
	7,  // 31: delivertrack.notification.NotificationService.SendBulkNotifications:output_type -> delivertrack.notification.SendBulkNotificationsResponse
	10, // 32: delivertrack.notification.NotificationService.GetNotificationHistory:output_type -> delivertrack.notification.GetNotificationHistoryResponse
	13, // 33: delivertrack.notification.NotificationService.UpdatePreferences:output_type -> delivertrack.notification.UpdatePreferencesResponse
	15, // 34: delivertrack.notification.NotificationService.GetPreferences:output_type -> delivertrack.notification.GetPreferencesResponse
	11, // 35: delivertrack.notification.NotificationService.Subscribe:output_type -> delivertrack.notification.Notification
	20, // 36: delivertrack.notification.NotificationService.MarkAsRead:output_type -> delivertrack.notification.MarkAsReadResponse
	22, // 37: delivertrack.notification.NotificationService.SendDeliveryUpdate:output_type -> delivertrack.notification.SendDeliveryUpdateResponse
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
