FROM nginx:1.27-alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom nginx config
COPY web/nginx.conf /etc/nginx/conf.d/default.conf

# Copy static frontend files
COPY web/index.html    /usr/share/nginx/html/
COPY web/css/          /usr/share/nginx/html/css/
COPY web/js/           /usr/share/nginx/html/js/

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
