// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: analytics.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_RecordEvent_FullMethodName          = "/delivertrack.analytics.AnalyticsService/RecordEvent"
	AnalyticsService_BatchRecordEvents_FullMethodName    = "/delivertrack.analytics.AnalyticsService/BatchRecordEvents"
	AnalyticsService_GetDeliveryMetrics_FullMethodName   = "/delivertrack.analytics.AnalyticsService/GetDeliveryMetrics"
	AnalyticsService_GetDriverPerformance_FullMethodName = "/delivertrack.analytics.AnalyticsService/GetDriverPerformance"
	AnalyticsService_GetCustomerAnalytics_FullMethodName = "/delivertrack.analytics.AnalyticsService/GetCustomerAnalytics"
	AnalyticsService_GetSystemMetrics_FullMethodName     = "/delivertrack.analytics.AnalyticsService/GetSystemMetrics"
	AnalyticsService_GenerateReport_FullMethodName       = "/delivertrack.analytics.AnalyticsService/GenerateReport"
	AnalyticsService_GetDashboard_FullMethodName         = "/delivertrack.analytics.AnalyticsService/GetDashboard"
	AnalyticsService_GetRouteEfficiency_FullMethodName   = "/delivertrack.analytics.AnalyticsService/GetRouteEfficiency"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	// Record a delivery event
	RecordEvent(ctx context.Context, in *RecordEventRequest, opts ...grpc.CallOption) (*RecordEventResponse, error)
	// Batch record events
	BatchRecordEvents(ctx context.Context, in *BatchRecordEventsRequest, opts ...grpc.CallOption) (*BatchRecordEventsResponse, error)
	// Get delivery metrics
	GetDeliveryMetrics(ctx context.Context, in *GetDeliveryMetricsRequest, opts ...grpc.CallOption) (*GetDeliveryMetricsResponse, error)
	// Get driver performance
	GetDriverPerformance(ctx context.Context, in *GetDriverPerformanceRequest, opts ...grpc.CallOption) (*GetDriverPerformanceResponse, error)
	// Get customer analytics
	GetCustomerAnalytics(ctx context.Context, in *GetCustomerAnalyticsRequest, opts ...grpc.CallOption) (*GetCustomerAnalyticsResponse, error)
	// Get system metrics
	GetSystemMetrics(ctx context.Context, in *GetSystemMetricsRequest, opts ...grpc.CallOption) (*GetSystemMetricsResponse, error)
	// Generate report
	GenerateReport(ctx context.Context, in *GenerateReportRequest, opts ...grpc.CallOption) (*GenerateReportResponse, error)
	// Get real-time dashboard
	GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error)
	// Get route efficiency
	GetRouteEfficiency(ctx context.Context, in *GetRouteEfficiencyRequest, opts ...grpc.CallOption) (*GetRouteEfficiencyResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) RecordEvent(ctx context.Context, in *RecordEventRequest, opts ...grpc.CallOption) (*RecordEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordEventResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_RecordEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) BatchRecordEvents(ctx context.Context, in *BatchRecordEventsRequest, opts ...grpc.CallOption) (*BatchRecordEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchRecordEventsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_BatchRecordEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetDeliveryMetrics(ctx context.Context, in *GetDeliveryMetricsRequest, opts ...grpc.CallOption) (*GetDeliveryMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeliveryMetricsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDeliveryMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetDriverPerformance(ctx context.Context, in *GetDriverPerformanceRequest, opts ...grpc.CallOption) (*GetDriverPerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverPerformanceResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDriverPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetCustomerAnalytics(ctx context.Context, in *GetCustomerAnalyticsRequest, opts ...grpc.CallOption) (*GetCustomerAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetCustomerAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetSystemMetrics(ctx context.Context, in *GetSystemMetricsRequest, opts ...grpc.CallOption) (*GetSystemMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemMetricsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetSystemMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GenerateReport(ctx context.Context, in *GenerateReportRequest, opts ...grpc.CallOption) (*GenerateReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GenerateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetRouteEfficiency(ctx context.Context, in *GetRouteEfficiencyRequest, opts ...grpc.CallOption) (*GetRouteEfficiencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteEfficiencyResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetRouteEfficiency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	// Record a delivery event
	RecordEvent(context.Context, *RecordEventRequest) (*RecordEventResponse, error)
	// Batch record events
	BatchRecordEvents(context.Context, *BatchRecordEventsRequest) (*BatchRecordEventsResponse, error)
	// Get delivery metrics
	GetDeliveryMetrics(context.Context, *GetDeliveryMetricsRequest) (*GetDeliveryMetricsResponse, error)
	// Get driver performance
	GetDriverPerformance(context.Context, *GetDriverPerformanceRequest) (*GetDriverPerformanceResponse, error)
	// Get customer analytics
	GetCustomerAnalytics(context.Context, *GetCustomerAnalyticsRequest) (*GetCustomerAnalyticsResponse, error)
	// Get system metrics
	GetSystemMetrics(context.Context, *GetSystemMetricsRequest) (*GetSystemMetricsResponse, error)
	// Generate report
	GenerateReport(context.Context, *GenerateReportRequest) (*GenerateReportResponse, error)
	// Get real-time dashboard
	GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error)
	// Get route efficiency
	GetRouteEfficiency(context.Context, *GetRouteEfficiencyRequest) (*GetRouteEfficiencyResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) RecordEvent(context.Context, *RecordEventRequest) (*RecordEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordEvent not implemented")
}
func (UnimplementedAnalyticsServiceServer) BatchRecordEvents(context.Context, *BatchRecordEventsRequest) (*BatchRecordEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchRecordEvents not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDeliveryMetrics(context.Context, *GetDeliveryMetricsRequest) (*GetDeliveryMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryMetrics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDriverPerformance(context.Context, *GetDriverPerformanceRequest) (*GetDriverPerformanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverPerformance not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetCustomerAnalytics(context.Context, *GetCustomerAnalyticsRequest) (*GetCustomerAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCustomerAnalytics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetSystemMetrics(context.Context, *GetSystemMetricsRequest) (*GetSystemMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemMetrics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GenerateReport(context.Context, *GenerateReportRequest) (*GenerateReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetRouteEfficiency(context.Context, *GetRouteEfficiencyRequest) (*GetRouteEfficiencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRouteEfficiency not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_RecordEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).RecordEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_RecordEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).RecordEvent(ctx, req.(*RecordEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_BatchRecordEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRecordEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).BatchRecordEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_BatchRecordEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).BatchRecordEvents(ctx, req.(*BatchRecordEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDeliveryMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDeliveryMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDeliveryMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDeliveryMetrics(ctx, req.(*GetDeliveryMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDriverPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDriverPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDriverPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDriverPerformance(ctx, req.(*GetDriverPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetCustomerAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetCustomerAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetCustomerAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetCustomerAnalytics(ctx, req.(*GetCustomerAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetSystemMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetSystemMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetSystemMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetSystemMetrics(ctx, req.(*GetSystemMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GenerateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GenerateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GenerateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GenerateReport(ctx, req.(*GenerateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDashboard(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetRouteEfficiency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteEfficiencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetRouteEfficiency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetRouteEfficiency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetRouteEfficiency(ctx, req.(*GetRouteEfficiencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delivertrack.analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordEvent",
			Handler:    _AnalyticsService_RecordEvent_Handler,
		},
		{
			MethodName: "BatchRecordEvents",
			Handler:    _AnalyticsService_BatchRecordEvents_Handler,
		},
		{
			MethodName: "GetDeliveryMetrics",
			Handler:    _AnalyticsService_GetDeliveryMetrics_Handler,
		},
		{
			MethodName: "GetDriverPerformance",
			Handler:    _AnalyticsService_GetDriverPerformance_Handler,
		},
		{
			MethodName: "GetCustomerAnalytics",
			Handler:    _AnalyticsService_GetCustomerAnalytics_Handler,
		},
		{
			MethodName: "GetSystemMetrics",
			Handler:    _AnalyticsService_GetSystemMetrics_Handler,
		},
		{
			MethodName: "GenerateReport",
			Handler:    _AnalyticsService_GenerateReport_Handler,
		},
		{
			MethodName: "GetDashboard",
			Handler:    _AnalyticsService_GetDashboard_Handler,
		},
		{
			MethodName: "GetRouteEfficiency",
			Handler:    _AnalyticsService_GetRouteEfficiency_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics.proto",
}
