// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: analytics.proto

package analytics

import (
	common "github.com/Keneke-Einar/delivertrack/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AggregationLevel int32

const (
	AggregationLevel_AGGREGATION_LEVEL_UNSPECIFIED AggregationLevel = 0
	AggregationLevel_AGGREGATION_LEVEL_HOURLY      AggregationLevel = 1
	AggregationLevel_AGGREGATION_LEVEL_DAILY       AggregationLevel = 2
	AggregationLevel_AGGREGATION_LEVEL_WEEKLY      AggregationLevel = 3
	AggregationLevel_AGGREGATION_LEVEL_MONTHLY     AggregationLevel = 4
)

// Enum value maps for AggregationLevel.
var (
	AggregationLevel_name = map[int32]string{
		0: "AGGREGATION_LEVEL_UNSPECIFIED",
		1: "AGGREGATION_LEVEL_HOURLY",
		2: "AGGREGATION_LEVEL_DAILY",
		3: "AGGREGATION_LEVEL_WEEKLY",
		4: "AGGREGATION_LEVEL_MONTHLY",
	}
	AggregationLevel_value = map[string]int32{
		"AGGREGATION_LEVEL_UNSPECIFIED": 0,
		"AGGREGATION_LEVEL_HOURLY":      1,
		"AGGREGATION_LEVEL_DAILY":       2,
		"AGGREGATION_LEVEL_WEEKLY":      3,
		"AGGREGATION_LEVEL_MONTHLY":     4,
	}
)

func (x AggregationLevel) Enum() *AggregationLevel {
	p := new(AggregationLevel)
	*p = x
	return p
}

func (x AggregationLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregationLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_proto_enumTypes[0].Descriptor()
}

func (AggregationLevel) Type() protoreflect.EnumType {
	return &file_analytics_proto_enumTypes[0]
}

func (x AggregationLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggregationLevel.Descriptor instead.
func (AggregationLevel) EnumDescriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

type ReportType int32

const (
	ReportType_REPORT_TYPE_UNSPECIFIED        ReportType = 0
	ReportType_REPORT_TYPE_DELIVERY_SUMMARY   ReportType = 1
	ReportType_REPORT_TYPE_DRIVER_PERFORMANCE ReportType = 2
	ReportType_REPORT_TYPE_CUSTOMER_ANALYTICS ReportType = 3
	ReportType_REPORT_TYPE_FINANCIAL          ReportType = 4
	ReportType_REPORT_TYPE_OPERATIONAL        ReportType = 5
)

// Enum value maps for ReportType.
var (
	ReportType_name = map[int32]string{
		0: "REPORT_TYPE_UNSPECIFIED",
		1: "REPORT_TYPE_DELIVERY_SUMMARY",
		2: "REPORT_TYPE_DRIVER_PERFORMANCE",
		3: "REPORT_TYPE_CUSTOMER_ANALYTICS",
		4: "REPORT_TYPE_FINANCIAL",
		5: "REPORT_TYPE_OPERATIONAL",
	}
	ReportType_value = map[string]int32{
		"REPORT_TYPE_UNSPECIFIED":        0,
		"REPORT_TYPE_DELIVERY_SUMMARY":   1,
		"REPORT_TYPE_DRIVER_PERFORMANCE": 2,
		"REPORT_TYPE_CUSTOMER_ANALYTICS": 3,
		"REPORT_TYPE_FINANCIAL":          4,
		"REPORT_TYPE_OPERATIONAL":        5,
	}
)

func (x ReportType) Enum() *ReportType {
	p := new(ReportType)
	*p = x
	return p
}

func (x ReportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportType) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_proto_enumTypes[1].Descriptor()
}

func (ReportType) Type() protoreflect.EnumType {
	return &file_analytics_proto_enumTypes[1]
}

func (x ReportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportType.Descriptor instead.
func (ReportType) EnumDescriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

type ReportFormat int32

const (
	ReportFormat_REPORT_FORMAT_UNSPECIFIED ReportFormat = 0
	ReportFormat_REPORT_FORMAT_PDF         ReportFormat = 1
	ReportFormat_REPORT_FORMAT_CSV         ReportFormat = 2
	ReportFormat_REPORT_FORMAT_EXCEL       ReportFormat = 3
	ReportFormat_REPORT_FORMAT_JSON        ReportFormat = 4
)

// Enum value maps for ReportFormat.
var (
	ReportFormat_name = map[int32]string{
		0: "REPORT_FORMAT_UNSPECIFIED",
		1: "REPORT_FORMAT_PDF",
		2: "REPORT_FORMAT_CSV",
		3: "REPORT_FORMAT_EXCEL",
		4: "REPORT_FORMAT_JSON",
	}
	ReportFormat_value = map[string]int32{
		"REPORT_FORMAT_UNSPECIFIED": 0,
		"REPORT_FORMAT_PDF":         1,
		"REPORT_FORMAT_CSV":         2,
		"REPORT_FORMAT_EXCEL":       3,
		"REPORT_FORMAT_JSON":        4,
	}
)

func (x ReportFormat) Enum() *ReportFormat {
	p := new(ReportFormat)
	*p = x
	return p
}

func (x ReportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_proto_enumTypes[2].Descriptor()
}

func (ReportFormat) Type() protoreflect.EnumType {
	return &file_analytics_proto_enumTypes[2]
}

func (x ReportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportFormat.Descriptor instead.
func (ReportFormat) EnumDescriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

type DashboardType int32

const (
	DashboardType_DASHBOARD_TYPE_UNSPECIFIED DashboardType = 0
	DashboardType_DASHBOARD_TYPE_OPERATIONS  DashboardType = 1
	DashboardType_DASHBOARD_TYPE_DRIVER      DashboardType = 2
	DashboardType_DASHBOARD_TYPE_CUSTOMER    DashboardType = 3
	DashboardType_DASHBOARD_TYPE_EXECUTIVE   DashboardType = 4
)

// Enum value maps for DashboardType.
var (
	DashboardType_name = map[int32]string{
		0: "DASHBOARD_TYPE_UNSPECIFIED",
		1: "DASHBOARD_TYPE_OPERATIONS",
		2: "DASHBOARD_TYPE_DRIVER",
		3: "DASHBOARD_TYPE_CUSTOMER",
		4: "DASHBOARD_TYPE_EXECUTIVE",
	}
	DashboardType_value = map[string]int32{
		"DASHBOARD_TYPE_UNSPECIFIED": 0,
		"DASHBOARD_TYPE_OPERATIONS":  1,
		"DASHBOARD_TYPE_DRIVER":      2,
		"DASHBOARD_TYPE_CUSTOMER":    3,
		"DASHBOARD_TYPE_EXECUTIVE":   4,
	}
)

func (x DashboardType) Enum() *DashboardType {
	p := new(DashboardType)
	*p = x
	return p
}

func (x DashboardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DashboardType) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_proto_enumTypes[3].Descriptor()
}

func (DashboardType) Type() protoreflect.EnumType {
	return &file_analytics_proto_enumTypes[3]
}

func (x DashboardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DashboardType.Descriptor instead.
func (DashboardType) EnumDescriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

type ChartType int32

const (
	ChartType_CHART_TYPE_UNSPECIFIED ChartType = 0
	ChartType_CHART_TYPE_LINE        ChartType = 1
	ChartType_CHART_TYPE_BAR         ChartType = 2
	ChartType_CHART_TYPE_PIE         ChartType = 3
	ChartType_CHART_TYPE_AREA        ChartType = 4
)

// Enum value maps for ChartType.
var (
	ChartType_name = map[int32]string{
		0: "CHART_TYPE_UNSPECIFIED",
		1: "CHART_TYPE_LINE",
		2: "CHART_TYPE_BAR",
		3: "CHART_TYPE_PIE",
		4: "CHART_TYPE_AREA",
	}
	ChartType_value = map[string]int32{
		"CHART_TYPE_UNSPECIFIED": 0,
		"CHART_TYPE_LINE":        1,
		"CHART_TYPE_BAR":         2,
		"CHART_TYPE_PIE":         3,
		"CHART_TYPE_AREA":        4,
	}
)

func (x ChartType) Enum() *ChartType {
	p := new(ChartType)
	*p = x
	return p
}

func (x ChartType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChartType) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_proto_enumTypes[4].Descriptor()
}

func (ChartType) Type() protoreflect.EnumType {
	return &file_analytics_proto_enumTypes[4]
}

func (x ChartType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChartType.Descriptor instead.
func (ChartType) EnumDescriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

type Trend int32

const (
	Trend_TREND_UNSPECIFIED Trend = 0
	Trend_TREND_UP          Trend = 1
	Trend_TREND_DOWN        Trend = 2
	Trend_TREND_STABLE      Trend = 3
)

// Enum value maps for Trend.
var (
	Trend_name = map[int32]string{
		0: "TREND_UNSPECIFIED",
		1: "TREND_UP",
		2: "TREND_DOWN",
		3: "TREND_STABLE",
	}
	Trend_value = map[string]int32{
		"TREND_UNSPECIFIED": 0,
		"TREND_UP":          1,
		"TREND_DOWN":        2,
		"TREND_STABLE":      3,
	}
)

func (x Trend) Enum() *Trend {
	p := new(Trend)
	*p = x
	return p
}

func (x Trend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Trend) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_proto_enumTypes[5].Descriptor()
}

func (Trend) Type() protoreflect.EnumType {
	return &file_analytics_proto_enumTypes[5]
}

func (x Trend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Trend.Descriptor instead.
func (Trend) EnumDescriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{5}
}

type AlertSeverity int32

const (
	AlertSeverity_ALERT_SEVERITY_UNSPECIFIED AlertSeverity = 0
	AlertSeverity_ALERT_SEVERITY_INFO        AlertSeverity = 1
	AlertSeverity_ALERT_SEVERITY_WARNING     AlertSeverity = 2
	AlertSeverity_ALERT_SEVERITY_ERROR       AlertSeverity = 3
	AlertSeverity_ALERT_SEVERITY_CRITICAL    AlertSeverity = 4
)

// Enum value maps for AlertSeverity.
var (
	AlertSeverity_name = map[int32]string{
		0: "ALERT_SEVERITY_UNSPECIFIED",
		1: "ALERT_SEVERITY_INFO",
		2: "ALERT_SEVERITY_WARNING",
		3: "ALERT_SEVERITY_ERROR",
		4: "ALERT_SEVERITY_CRITICAL",
	}
	AlertSeverity_value = map[string]int32{
		"ALERT_SEVERITY_UNSPECIFIED": 0,
		"ALERT_SEVERITY_INFO":        1,
		"ALERT_SEVERITY_WARNING":     2,
		"ALERT_SEVERITY_ERROR":       3,
		"ALERT_SEVERITY_CRITICAL":    4,
	}
)

func (x AlertSeverity) Enum() *AlertSeverity {
	p := new(AlertSeverity)
	*p = x
	return p
}

func (x AlertSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_proto_enumTypes[6].Descriptor()
}

func (AlertSeverity) Type() protoreflect.EnumType {
	return &file_analytics_proto_enumTypes[6]
}

func (x AlertSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertSeverity.Descriptor instead.
func (AlertSeverity) EnumDescriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{6}
}

type RecordEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EntityType    string                 `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // delivery, driver, customer, etc.
	EntityId      string                 `protobuf:"bytes,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventRequest) Reset() {
	*x = RecordEventRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventRequest) ProtoMessage() {}

func (x *RecordEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventRequest.ProtoReflect.Descriptor instead.
func (*RecordEventRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *RecordEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RecordEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RecordEventRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *RecordEventRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *RecordEventRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *RecordEventRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RecordEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecordedAt    int64                  `protobuf:"varint,2,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventResponse) Reset() {
	*x = RecordEventResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventResponse) ProtoMessage() {}

func (x *RecordEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventResponse.ProtoReflect.Descriptor instead.
func (*RecordEventResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *RecordEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordEventResponse) GetRecordedAt() int64 {
	if x != nil {
		return x.RecordedAt
	}
	return 0
}

type BatchRecordEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RecordEventRequest  `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRecordEventsRequest) Reset() {
	*x = BatchRecordEventsRequest{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRecordEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRecordEventsRequest) ProtoMessage() {}

func (x *BatchRecordEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRecordEventsRequest.ProtoReflect.Descriptor instead.
func (*BatchRecordEventsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *BatchRecordEventsRequest) GetEvents() []*RecordEventRequest {
	if x != nil {
		return x.Events
	}
	return nil
}

type BatchRecordEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRecordEventsResponse) Reset() {
	*x = BatchRecordEventsResponse{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRecordEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRecordEventsResponse) ProtoMessage() {}

func (x *BatchRecordEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRecordEventsResponse.ProtoReflect.Descriptor instead.
func (*BatchRecordEventsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *BatchRecordEventsResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchRecordEventsResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

type GetDeliveryMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     *common.TimeRange      `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	DeliveryIds   []string               `protobuf:"bytes,2,rep,name=delivery_ids,json=deliveryIds,proto3" json:"delivery_ids,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Aggregation   AggregationLevel       `protobuf:"varint,4,opt,name=aggregation,proto3,enum=delivertrack.analytics.AggregationLevel" json:"aggregation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryMetricsRequest) Reset() {
	*x = GetDeliveryMetricsRequest{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryMetricsRequest) ProtoMessage() {}

func (x *GetDeliveryMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryMetricsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeliveryMetricsRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *GetDeliveryMetricsRequest) GetDeliveryIds() []string {
	if x != nil {
		return x.DeliveryIds
	}
	return nil
}

func (x *GetDeliveryMetricsRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetDeliveryMetricsRequest) GetAggregation() AggregationLevel {
	if x != nil {
		return x.Aggregation
	}
	return AggregationLevel_AGGREGATION_LEVEL_UNSPECIFIED
}

type GetDeliveryMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *DeliveryMetrics       `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	TimeSeries    []*TimeSeriesPoint     `protobuf:"bytes,2,rep,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryMetricsResponse) Reset() {
	*x = GetDeliveryMetricsResponse{}
	mi := &file_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryMetricsResponse) ProtoMessage() {}

func (x *GetDeliveryMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryMetricsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeliveryMetricsResponse) GetMetrics() *DeliveryMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetDeliveryMetricsResponse) GetTimeSeries() []*TimeSeriesPoint {
	if x != nil {
		return x.TimeSeries
	}
	return nil
}

type DeliveryMetrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalDeliveries      int32                  `protobuf:"varint,1,opt,name=total_deliveries,json=totalDeliveries,proto3" json:"total_deliveries,omitempty"`
	SuccessfulDeliveries int32                  `protobuf:"varint,2,opt,name=successful_deliveries,json=successfulDeliveries,proto3" json:"successful_deliveries,omitempty"`
	FailedDeliveries     int32                  `protobuf:"varint,3,opt,name=failed_deliveries,json=failedDeliveries,proto3" json:"failed_deliveries,omitempty"`
	CancelledDeliveries  int32                  `protobuf:"varint,4,opt,name=cancelled_deliveries,json=cancelledDeliveries,proto3" json:"cancelled_deliveries,omitempty"`
	SuccessRate          float64                `protobuf:"fixed64,5,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`                           // percentage
	AverageDeliveryTime  float64                `protobuf:"fixed64,6,opt,name=average_delivery_time,json=averageDeliveryTime,proto3" json:"average_delivery_time,omitempty"` // minutes
	AverageDistance      float64                `protobuf:"fixed64,7,opt,name=average_distance,json=averageDistance,proto3" json:"average_distance,omitempty"`               // km
	OnTimeDeliveries     int32                  `protobuf:"varint,8,opt,name=on_time_deliveries,json=onTimeDeliveries,proto3" json:"on_time_deliveries,omitempty"`
	OnTimeRate           float64                `protobuf:"fixed64,9,opt,name=on_time_rate,json=onTimeRate,proto3" json:"on_time_rate,omitempty"` // percentage
	AverageRating        float64                `protobuf:"fixed64,10,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	TotalRatingCount     int32                  `protobuf:"varint,11,opt,name=total_rating_count,json=totalRatingCount,proto3" json:"total_rating_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeliveryMetrics) Reset() {
	*x = DeliveryMetrics{}
	mi := &file_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryMetrics) ProtoMessage() {}

func (x *DeliveryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryMetrics.ProtoReflect.Descriptor instead.
func (*DeliveryMetrics) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *DeliveryMetrics) GetTotalDeliveries() int32 {
	if x != nil {
		return x.TotalDeliveries
	}
	return 0
}

func (x *DeliveryMetrics) GetSuccessfulDeliveries() int32 {
	if x != nil {
		return x.SuccessfulDeliveries
	}
	return 0
}

func (x *DeliveryMetrics) GetFailedDeliveries() int32 {
	if x != nil {
		return x.FailedDeliveries
	}
	return 0
}

func (x *DeliveryMetrics) GetCancelledDeliveries() int32 {
	if x != nil {
		return x.CancelledDeliveries
	}
	return 0
}

func (x *DeliveryMetrics) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *DeliveryMetrics) GetAverageDeliveryTime() float64 {
	if x != nil {
		return x.AverageDeliveryTime
	}
	return 0
}

func (x *DeliveryMetrics) GetAverageDistance() float64 {
	if x != nil {
		return x.AverageDistance
	}
	return 0
}

func (x *DeliveryMetrics) GetOnTimeDeliveries() int32 {
	if x != nil {
		return x.OnTimeDeliveries
	}
	return 0
}

func (x *DeliveryMetrics) GetOnTimeRate() float64 {
	if x != nil {
		return x.OnTimeRate
	}
	return 0
}

func (x *DeliveryMetrics) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *DeliveryMetrics) GetTotalRatingCount() int32 {
	if x != nil {
		return x.TotalRatingCount
	}
	return 0
}

type GetDriverPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TimeRange     *common.TimeRange      `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverPerformanceRequest) Reset() {
	*x = GetDriverPerformanceRequest{}
	mi := &file_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverPerformanceRequest) ProtoMessage() {}

func (x *GetDriverPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverPerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetDriverPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetDriverPerformanceRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetDriverPerformanceRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type GetDriverPerformanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Performance   *DriverPerformance     `protobuf:"bytes,1,opt,name=performance,proto3" json:"performance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverPerformanceResponse) Reset() {
	*x = GetDriverPerformanceResponse{}
	mi := &file_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverPerformanceResponse) ProtoMessage() {}

func (x *GetDriverPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverPerformanceResponse.ProtoReflect.Descriptor instead.
func (*GetDriverPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetDriverPerformanceResponse) GetPerformance() *DriverPerformance {
	if x != nil {
		return x.Performance
	}
	return nil
}

type DriverPerformance struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DriverId            string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TotalDeliveries     int32                  `protobuf:"varint,2,opt,name=total_deliveries,json=totalDeliveries,proto3" json:"total_deliveries,omitempty"`
	CompletedDeliveries int32                  `protobuf:"varint,3,opt,name=completed_deliveries,json=completedDeliveries,proto3" json:"completed_deliveries,omitempty"`
	FailedDeliveries    int32                  `protobuf:"varint,4,opt,name=failed_deliveries,json=failedDeliveries,proto3" json:"failed_deliveries,omitempty"`
	CompletionRate      float64                `protobuf:"fixed64,5,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`                  // percentage
	AverageDeliveryTime float64                `protobuf:"fixed64,6,opt,name=average_delivery_time,json=averageDeliveryTime,proto3" json:"average_delivery_time,omitempty"` // minutes
	TotalDistance       float64                `protobuf:"fixed64,7,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`                     // km
	AverageRating       float64                `protobuf:"fixed64,8,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	RatingCount         int32                  `protobuf:"varint,9,opt,name=rating_count,json=ratingCount,proto3" json:"rating_count,omitempty"`
	OnTimeDeliveries    int32                  `protobuf:"varint,10,opt,name=on_time_deliveries,json=onTimeDeliveries,proto3" json:"on_time_deliveries,omitempty"`
	OnTimeRate          float64                `protobuf:"fixed64,11,opt,name=on_time_rate,json=onTimeRate,proto3" json:"on_time_rate,omitempty"`                     // percentage
	EfficiencyScore     float64                `protobuf:"fixed64,12,opt,name=efficiency_score,json=efficiencyScore,proto3" json:"efficiency_score,omitempty"`        // 0-100
	TotalWorkingHours   int64                  `protobuf:"varint,13,opt,name=total_working_hours,json=totalWorkingHours,proto3" json:"total_working_hours,omitempty"` // seconds
	DeliveriesPerHour   float64                `protobuf:"fixed64,14,opt,name=deliveries_per_hour,json=deliveriesPerHour,proto3" json:"deliveries_per_hour,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DriverPerformance) Reset() {
	*x = DriverPerformance{}
	mi := &file_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverPerformance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverPerformance) ProtoMessage() {}

func (x *DriverPerformance) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverPerformance.ProtoReflect.Descriptor instead.
func (*DriverPerformance) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *DriverPerformance) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverPerformance) GetTotalDeliveries() int32 {
	if x != nil {
		return x.TotalDeliveries
	}
	return 0
}

func (x *DriverPerformance) GetCompletedDeliveries() int32 {
	if x != nil {
		return x.CompletedDeliveries
	}
	return 0
}

func (x *DriverPerformance) GetFailedDeliveries() int32 {
	if x != nil {
		return x.FailedDeliveries
	}
	return 0
}

func (x *DriverPerformance) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *DriverPerformance) GetAverageDeliveryTime() float64 {
	if x != nil {
		return x.AverageDeliveryTime
	}
	return 0
}

func (x *DriverPerformance) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *DriverPerformance) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *DriverPerformance) GetRatingCount() int32 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

func (x *DriverPerformance) GetOnTimeDeliveries() int32 {
	if x != nil {
		return x.OnTimeDeliveries
	}
	return 0
}

func (x *DriverPerformance) GetOnTimeRate() float64 {
	if x != nil {
		return x.OnTimeRate
	}
	return 0
}

func (x *DriverPerformance) GetEfficiencyScore() float64 {
	if x != nil {
		return x.EfficiencyScore
	}
	return 0
}

func (x *DriverPerformance) GetTotalWorkingHours() int64 {
	if x != nil {
		return x.TotalWorkingHours
	}
	return 0
}

func (x *DriverPerformance) GetDeliveriesPerHour() float64 {
	if x != nil {
		return x.DeliveriesPerHour
	}
	return 0
}

type GetCustomerAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	TimeRange     *common.TimeRange      `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerAnalyticsRequest) Reset() {
	*x = GetCustomerAnalyticsRequest{}
	mi := &file_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerAnalyticsRequest) ProtoMessage() {}

func (x *GetCustomerAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetCustomerAnalyticsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetCustomerAnalyticsRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type GetCustomerAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analytics     *CustomerAnalytics     `protobuf:"bytes,1,opt,name=analytics,proto3" json:"analytics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerAnalyticsResponse) Reset() {
	*x = GetCustomerAnalyticsResponse{}
	mi := &file_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerAnalyticsResponse) ProtoMessage() {}

func (x *GetCustomerAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *GetCustomerAnalyticsResponse) GetAnalytics() *CustomerAnalytics {
	if x != nil {
		return x.Analytics
	}
	return nil
}

type CustomerAnalytics struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	CustomerId              string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	TotalDeliveries         int32                  `protobuf:"varint,2,opt,name=total_deliveries,json=totalDeliveries,proto3" json:"total_deliveries,omitempty"`
	SuccessfulDeliveries    int32                  `protobuf:"varint,3,opt,name=successful_deliveries,json=successfulDeliveries,proto3" json:"successful_deliveries,omitempty"`
	FailedDeliveries        int32                  `protobuf:"varint,4,opt,name=failed_deliveries,json=failedDeliveries,proto3" json:"failed_deliveries,omitempty"`
	AverageDeliveryTime     float64                `protobuf:"fixed64,5,opt,name=average_delivery_time,json=averageDeliveryTime,proto3" json:"average_delivery_time,omitempty"` // minutes
	FrequentLocations       []*common.Location     `protobuf:"bytes,6,rep,name=frequent_locations,json=frequentLocations,proto3" json:"frequent_locations,omitempty"`
	DeliveryTimePreferences map[string]int32       `protobuf:"bytes,7,rep,name=delivery_time_preferences,json=deliveryTimePreferences,proto3" json:"delivery_time_preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // time slot -> count
	TotalSpent              float64                `protobuf:"fixed64,8,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
	CustomerSince           int64                  `protobuf:"varint,9,opt,name=customer_since,json=customerSince,proto3" json:"customer_since,omitempty"`
	SatisfactionScore       float64                `protobuf:"fixed64,10,opt,name=satisfaction_score,json=satisfactionScore,proto3" json:"satisfaction_score,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CustomerAnalytics) Reset() {
	*x = CustomerAnalytics{}
	mi := &file_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerAnalytics) ProtoMessage() {}

func (x *CustomerAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerAnalytics.ProtoReflect.Descriptor instead.
func (*CustomerAnalytics) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *CustomerAnalytics) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CustomerAnalytics) GetTotalDeliveries() int32 {
	if x != nil {
		return x.TotalDeliveries
	}
	return 0
}

func (x *CustomerAnalytics) GetSuccessfulDeliveries() int32 {
	if x != nil {
		return x.SuccessfulDeliveries
	}
	return 0
}

func (x *CustomerAnalytics) GetFailedDeliveries() int32 {
	if x != nil {
		return x.FailedDeliveries
	}
	return 0
}

func (x *CustomerAnalytics) GetAverageDeliveryTime() float64 {
	if x != nil {
		return x.AverageDeliveryTime
	}
	return 0
}

func (x *CustomerAnalytics) GetFrequentLocations() []*common.Location {
	if x != nil {
		return x.FrequentLocations
	}
	return nil
}

func (x *CustomerAnalytics) GetDeliveryTimePreferences() map[string]int32 {
	if x != nil {
		return x.DeliveryTimePreferences
	}
	return nil
}

func (x *CustomerAnalytics) GetTotalSpent() float64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

func (x *CustomerAnalytics) GetCustomerSince() int64 {
	if x != nil {
		return x.CustomerSince
	}
	return 0
}

func (x *CustomerAnalytics) GetSatisfactionScore() float64 {
	if x != nil {
		return x.SatisfactionScore
	}
	return 0
}

type GetSystemMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     *common.TimeRange      `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemMetricsRequest) Reset() {
	*x = GetSystemMetricsRequest{}
	mi := &file_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemMetricsRequest) ProtoMessage() {}

func (x *GetSystemMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetSystemMetricsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *GetSystemMetricsRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type GetSystemMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *SystemMetrics         `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemMetricsResponse) Reset() {
	*x = GetSystemMetricsResponse{}
	mi := &file_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemMetricsResponse) ProtoMessage() {}

func (x *GetSystemMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetSystemMetricsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *GetSystemMetricsResponse) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type SystemMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ActiveDrivers       int32                  `protobuf:"varint,1,opt,name=active_drivers,json=activeDrivers,proto3" json:"active_drivers,omitempty"`
	ActiveDeliveries    int32                  `protobuf:"varint,2,opt,name=active_deliveries,json=activeDeliveries,proto3" json:"active_deliveries,omitempty"`
	PendingDeliveries   int32                  `protobuf:"varint,3,opt,name=pending_deliveries,json=pendingDeliveries,proto3" json:"pending_deliveries,omitempty"`
	AverageResponseTime float64                `protobuf:"fixed64,4,opt,name=average_response_time,json=averageResponseTime,proto3" json:"average_response_time,omitempty"` // ms
	SystemUptime        float64                `protobuf:"fixed64,5,opt,name=system_uptime,json=systemUptime,proto3" json:"system_uptime,omitempty"`                        // percentage
	TotalRequests       int64                  `protobuf:"varint,6,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	FailedRequests      int64                  `protobuf:"varint,7,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	ErrorRate           float64                `protobuf:"fixed64,8,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"` // percentage
	ApiCallCounts       map[string]int64       `protobuf:"bytes,9,rep,name=api_call_counts,json=apiCallCounts,proto3" json:"api_call_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ResourceUsage       *ResourceUsage         `protobuf:"bytes,10,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *SystemMetrics) GetActiveDrivers() int32 {
	if x != nil {
		return x.ActiveDrivers
	}
	return 0
}

func (x *SystemMetrics) GetActiveDeliveries() int32 {
	if x != nil {
		return x.ActiveDeliveries
	}
	return 0
}

func (x *SystemMetrics) GetPendingDeliveries() int32 {
	if x != nil {
		return x.PendingDeliveries
	}
	return 0
}

func (x *SystemMetrics) GetAverageResponseTime() float64 {
	if x != nil {
		return x.AverageResponseTime
	}
	return 0
}

func (x *SystemMetrics) GetSystemUptime() float64 {
	if x != nil {
		return x.SystemUptime
	}
	return 0
}

func (x *SystemMetrics) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *SystemMetrics) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *SystemMetrics) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *SystemMetrics) GetApiCallCounts() map[string]int64 {
	if x != nil {
		return x.ApiCallCounts
	}
	return nil
}

func (x *SystemMetrics) GetResourceUsage() *ResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

type ResourceUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`          // percentage
	MemoryUsage   float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"` // percentage
	DiskUsage     float64                `protobuf:"fixed64,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`       // percentage
	NetworkIn     int64                  `protobuf:"varint,4,opt,name=network_in,json=networkIn,proto3" json:"network_in,omitempty"`        // bytes
	NetworkOut    int64                  `protobuf:"varint,5,opt,name=network_out,json=networkOut,proto3" json:"network_out,omitempty"`     // bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *ResourceUsage) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ResourceUsage) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ResourceUsage) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *ResourceUsage) GetNetworkIn() int64 {
	if x != nil {
		return x.NetworkIn
	}
	return 0
}

func (x *ResourceUsage) GetNetworkOut() int64 {
	if x != nil {
		return x.NetworkOut
	}
	return 0
}

type GenerateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ReportType             `protobuf:"varint,1,opt,name=type,proto3,enum=delivertrack.analytics.ReportType" json:"type,omitempty"`
	TimeRange     *common.TimeRange      `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // driver_id, customer_id, etc.
	Format        ReportFormat           `protobuf:"varint,4,opt,name=format,proto3,enum=delivertrack.analytics.ReportFormat" json:"format,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest) Reset() {
	*x = GenerateReportRequest{}
	mi := &file_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest) ProtoMessage() {}

func (x *GenerateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{17}
}

func (x *GenerateReportRequest) GetType() ReportType {
	if x != nil {
		return x.Type
	}
	return ReportType_REPORT_TYPE_UNSPECIFIED
}

func (x *GenerateReportRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *GenerateReportRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *GenerateReportRequest) GetFormat() ReportFormat {
	if x != nil {
		return x.Format
	}
	return ReportFormat_REPORT_FORMAT_UNSPECIFIED
}

func (x *GenerateReportRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GenerateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	GeneratedAt   int64                  `protobuf:"varint,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportResponse) Reset() {
	*x = GenerateReportResponse{}
	mi := &file_analytics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportResponse) ProtoMessage() {}

func (x *GenerateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportResponse.ProtoReflect.Descriptor instead.
func (*GenerateReportResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{18}
}

func (x *GenerateReportResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *GenerateReportResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *GenerateReportResponse) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

func (x *GenerateReportResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DashboardType          `protobuf:"varint,1,opt,name=type,proto3,enum=delivertrack.analytics.DashboardType" json:"type,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // optional, for driver/customer specific dashboards
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_analytics_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{19}
}

func (x *GetDashboardRequest) GetType() DashboardType {
	if x != nil {
		return x.Type
	}
	return DashboardType_DASHBOARD_TYPE_UNSPECIFIED
}

func (x *GetDashboardRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type GetDashboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dashboard     *Dashboard             `protobuf:"bytes,1,opt,name=dashboard,proto3" json:"dashboard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_analytics_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{20}
}

func (x *GetDashboardResponse) GetDashboard() *Dashboard {
	if x != nil {
		return x.Dashboard
	}
	return nil
}

type Dashboard struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	LastUpdated     int64                  `protobuf:"varint,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	DeliverySummary *DeliveryMetrics       `protobuf:"bytes,3,opt,name=delivery_summary,json=deliverySummary,proto3" json:"delivery_summary,omitempty"`
	Kpis            []*KPI                 `protobuf:"bytes,4,rep,name=kpis,proto3" json:"kpis,omitempty"`
	Charts          []*Chart               `protobuf:"bytes,5,rep,name=charts,proto3" json:"charts,omitempty"`
	Alerts          []*Alert               `protobuf:"bytes,6,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Dashboard) Reset() {
	*x = Dashboard{}
	mi := &file_analytics_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dashboard) ProtoMessage() {}

func (x *Dashboard) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dashboard.ProtoReflect.Descriptor instead.
func (*Dashboard) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{21}
}

func (x *Dashboard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Dashboard) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *Dashboard) GetDeliverySummary() *DeliveryMetrics {
	if x != nil {
		return x.DeliverySummary
	}
	return nil
}

func (x *Dashboard) GetKpis() []*KPI {
	if x != nil {
		return x.Kpis
	}
	return nil
}

func (x *Dashboard) GetCharts() []*Chart {
	if x != nil {
		return x.Charts
	}
	return nil
}

func (x *Dashboard) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type KPI struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value            float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit             string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	ChangePercentage float64                `protobuf:"fixed64,4,opt,name=change_percentage,json=changePercentage,proto3" json:"change_percentage,omitempty"` // compared to previous period
	Trend            Trend                  `protobuf:"varint,5,opt,name=trend,proto3,enum=delivertrack.analytics.Trend" json:"trend,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KPI) Reset() {
	*x = KPI{}
	mi := &file_analytics_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KPI) ProtoMessage() {}

func (x *KPI) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KPI.ProtoReflect.Descriptor instead.
func (*KPI) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{22}
}

func (x *KPI) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KPI) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *KPI) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *KPI) GetChangePercentage() float64 {
	if x != nil {
		return x.ChangePercentage
	}
	return 0
}

func (x *KPI) GetTrend() Trend {
	if x != nil {
		return x.Trend
	}
	return Trend_TREND_UNSPECIFIED
}

type Chart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type          ChartType              `protobuf:"varint,2,opt,name=type,proto3,enum=delivertrack.analytics.ChartType" json:"type,omitempty"`
	Data          []*TimeSeriesPoint     `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart) Reset() {
	*x = Chart{}
	mi := &file_analytics_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart) ProtoMessage() {}

func (x *Chart) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart.ProtoReflect.Descriptor instead.
func (*Chart) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{23}
}

func (x *Chart) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chart) GetType() ChartType {
	if x != nil {
		return x.Type
	}
	return ChartType_CHART_TYPE_UNSPECIFIED
}

func (x *Chart) GetData() []*TimeSeriesPoint {
	if x != nil {
		return x.Data
	}
	return nil
}

type TimeSeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesPoint) Reset() {
	*x = TimeSeriesPoint{}
	mi := &file_analytics_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesPoint) ProtoMessage() {}

func (x *TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesPoint.ProtoReflect.Descriptor instead.
func (*TimeSeriesPoint) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{24}
}

func (x *TimeSeriesPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TimeSeriesPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TimeSeriesPoint) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Severity      AlertSeverity          `protobuf:"varint,2,opt,name=severity,proto3,enum=delivertrack.analytics.AlertSeverity" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Acknowledged  bool                   `protobuf:"varint,5,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_analytics_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{25}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_ALERT_SEVERITY_UNSPECIFIED
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Alert) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type GetRouteEfficiencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TimeRange     *common.TimeRange      `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteEfficiencyRequest) Reset() {
	*x = GetRouteEfficiencyRequest{}
	mi := &file_analytics_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteEfficiencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteEfficiencyRequest) ProtoMessage() {}

func (x *GetRouteEfficiencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteEfficiencyRequest.ProtoReflect.Descriptor instead.
func (*GetRouteEfficiencyRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{26}
}

func (x *GetRouteEfficiencyRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetRouteEfficiencyRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type GetRouteEfficiencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Efficiency    *RouteEfficiency       `protobuf:"bytes,1,opt,name=efficiency,proto3" json:"efficiency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteEfficiencyResponse) Reset() {
	*x = GetRouteEfficiencyResponse{}
	mi := &file_analytics_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteEfficiencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteEfficiencyResponse) ProtoMessage() {}

func (x *GetRouteEfficiencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteEfficiencyResponse.ProtoReflect.Descriptor instead.
func (*GetRouteEfficiencyResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{27}
}

func (x *GetRouteEfficiencyResponse) GetEfficiency() *RouteEfficiency {
	if x != nil {
		return x.Efficiency
	}
	return nil
}

type RouteEfficiency struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalDistance   float64                `protobuf:"fixed64,1,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`       // km
	OptimalDistance float64                `protobuf:"fixed64,2,opt,name=optimal_distance,json=optimalDistance,proto3" json:"optimal_distance,omitempty"` // km
	EfficiencyScore float64                `protobuf:"fixed64,3,opt,name=efficiency_score,json=efficiencyScore,proto3" json:"efficiency_score,omitempty"` // 0-100
	AverageSpeed    float64                `protobuf:"fixed64,4,opt,name=average_speed,json=averageSpeed,proto3" json:"average_speed,omitempty"`          // km/h
	TotalStops      int32                  `protobuf:"varint,5,opt,name=total_stops,json=totalStops,proto3" json:"total_stops,omitempty"`
	IdleTime        float64                `protobuf:"fixed64,6,opt,name=idle_time,json=idleTime,proto3" json:"idle_time,omitempty"`                   // minutes
	DrivingTime     float64                `protobuf:"fixed64,7,opt,name=driving_time,json=drivingTime,proto3" json:"driving_time,omitempty"`          // minutes
	FuelEfficiency  float64                `protobuf:"fixed64,8,opt,name=fuel_efficiency,json=fuelEfficiency,proto3" json:"fuel_efficiency,omitempty"` // km/l
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteEfficiency) Reset() {
	*x = RouteEfficiency{}
	mi := &file_analytics_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEfficiency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEfficiency) ProtoMessage() {}

func (x *RouteEfficiency) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEfficiency.ProtoReflect.Descriptor instead.
func (*RouteEfficiency) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{28}
}

func (x *RouteEfficiency) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *RouteEfficiency) GetOptimalDistance() float64 {
	if x != nil {
		return x.OptimalDistance
	}
	return 0
}

func (x *RouteEfficiency) GetEfficiencyScore() float64 {
	if x != nil {
		return x.EfficiencyScore
	}
	return 0
}

func (x *RouteEfficiency) GetAverageSpeed() float64 {
	if x != nil {
		return x.AverageSpeed
	}
	return 0
}

func (x *RouteEfficiency) GetTotalStops() int32 {
	if x != nil {
		return x.TotalStops
	}
	return 0
}

func (x *RouteEfficiency) GetIdleTime() float64 {
	if x != nil {
		return x.IdleTime
	}
	return 0
}

func (x *RouteEfficiency) GetDrivingTime() float64 {
	if x != nil {
		return x.DrivingTime
	}
	return 0
}

func (x *RouteEfficiency) GetFuelEfficiency() float64 {
	if x != nil {
		return x.FuelEfficiency
	}
	return 0
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\x16delivertrack.analytics\x1a\fcommon.proto\"\xc5\x02\n" +
	"\x12RecordEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\tR\bentityId\x12Z\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2:.delivertrack.analytics.RecordEventRequest.PropertiesEntryR\n" +
	"properties\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x13RecordEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vrecorded_at\x18\x02 \x01(\x03R\n" +
	"recordedAt\"^\n" +
	"\x18BatchRecordEventsRequest\x12B\n" +
	"\x06events\x18\x01 \x03(\v2*.delivertrack.analytics.RecordEventRequestR\x06events\"c\n" +
	"\x19BatchRecordEventsResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\"\xe6\x01\n" +
	"\x19GetDeliveryMetricsRequest\x12=\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2\x1e.delivertrack.common.TimeRangeR\ttimeRange\x12!\n" +
	"\fdelivery_ids\x18\x02 \x03(\tR\vdeliveryIds\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12J\n" +
	"\vaggregation\x18\x04 \x01(\x0e2(.delivertrack.analytics.AggregationLevelR\vaggregation\"\xa9\x01\n" +
	"\x1aGetDeliveryMetricsResponse\x12A\n" +
	"\ametrics\x18\x01 \x01(\v2'.delivertrack.analytics.DeliveryMetricsR\ametrics\x12H\n" +
	"\vtime_series\x18\x02 \x03(\v2'.delivertrack.analytics.TimeSeriesPointR\n" +
	"timeSeries\"\xf8\x03\n" +
	"\x0fDeliveryMetrics\x12)\n" +
	"\x10total_deliveries\x18\x01 \x01(\x05R\x0ftotalDeliveries\x123\n" +
	"\x15successful_deliveries\x18\x02 \x01(\x05R\x14successfulDeliveries\x12+\n" +
	"\x11failed_deliveries\x18\x03 \x01(\x05R\x10failedDeliveries\x121\n" +
	"\x14cancelled_deliveries\x18\x04 \x01(\x05R\x13cancelledDeliveries\x12!\n" +
	"\fsuccess_rate\x18\x05 \x01(\x01R\vsuccessRate\x122\n" +
	"\x15average_delivery_time\x18\x06 \x01(\x01R\x13averageDeliveryTime\x12)\n" +
	"\x10average_distance\x18\a \x01(\x01R\x0faverageDistance\x12,\n" +
	"\x12on_time_deliveries\x18\b \x01(\x05R\x10onTimeDeliveries\x12 \n" +
	"\fon_time_rate\x18\t \x01(\x01R\n" +
	"onTimeRate\x12%\n" +
	"\x0eaverage_rating\x18\n" +
	" \x01(\x01R\raverageRating\x12,\n" +
	"\x12total_rating_count\x18\v \x01(\x05R\x10totalRatingCount\"y\n" +
	"\x1bGetDriverPerformanceRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12=\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2\x1e.delivertrack.common.TimeRangeR\ttimeRange\"k\n" +
	"\x1cGetDriverPerformanceResponse\x12K\n" +
	"\vperformance\x18\x01 \x01(\v2).delivertrack.analytics.DriverPerformanceR\vperformance\"\xe4\x04\n" +
	"\x11DriverPerformance\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12)\n" +
	"\x10total_deliveries\x18\x02 \x01(\x05R\x0ftotalDeliveries\x121\n" +
	"\x14completed_deliveries\x18\x03 \x01(\x05R\x13completedDeliveries\x12+\n" +
	"\x11failed_deliveries\x18\x04 \x01(\x05R\x10failedDeliveries\x12'\n" +
	"\x0fcompletion_rate\x18\x05 \x01(\x01R\x0ecompletionRate\x122\n" +
	"\x15average_delivery_time\x18\x06 \x01(\x01R\x13averageDeliveryTime\x12%\n" +
	"\x0etotal_distance\x18\a \x01(\x01R\rtotalDistance\x12%\n" +
	"\x0eaverage_rating\x18\b \x01(\x01R\raverageRating\x12!\n" +
	"\frating_count\x18\t \x01(\x05R\vratingCount\x12,\n" +
	"\x12on_time_deliveries\x18\n" +
	" \x01(\x05R\x10onTimeDeliveries\x12 \n" +
	"\fon_time_rate\x18\v \x01(\x01R\n" +
	"onTimeRate\x12)\n" +
	"\x10efficiency_score\x18\f \x01(\x01R\x0fefficiencyScore\x12.\n" +
	"\x13total_working_hours\x18\r \x01(\x03R\x11totalWorkingHours\x12.\n" +
	"\x13deliveries_per_hour\x18\x0e \x01(\x01R\x11deliveriesPerHour\"}\n" +
	"\x1bGetCustomerAnalyticsRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12=\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2\x1e.delivertrack.common.TimeRangeR\ttimeRange\"g\n" +
	"\x1cGetCustomerAnalyticsResponse\x12G\n" +
	"\tanalytics\x18\x01 \x01(\v2).delivertrack.analytics.CustomerAnalyticsR\tanalytics\"\x8b\x05\n" +
	"\x11CustomerAnalytics\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12)\n" +
	"\x10total_deliveries\x18\x02 \x01(\x05R\x0ftotalDeliveries\x123\n" +
	"\x15successful_deliveries\x18\x03 \x01(\x05R\x14successfulDeliveries\x12+\n" +
	"\x11failed_deliveries\x18\x04 \x01(\x05R\x10failedDeliveries\x122\n" +
	"\x15average_delivery_time\x18\x05 \x01(\x01R\x13averageDeliveryTime\x12L\n" +
	"\x12frequent_locations\x18\x06 \x03(\v2\x1d.delivertrack.common.LocationR\x11frequentLocations\x12\x82\x01\n" +
	"\x19delivery_time_preferences\x18\a \x03(\v2F.delivertrack.analytics.CustomerAnalytics.DeliveryTimePreferencesEntryR\x17deliveryTimePreferences\x12\x1f\n" +
	"\vtotal_spent\x18\b \x01(\x01R\n" +
	"totalSpent\x12%\n" +
	"\x0ecustomer_since\x18\t \x01(\x03R\rcustomerSince\x12-\n" +
	"\x12satisfaction_score\x18\n" +
	" \x01(\x01R\x11satisfactionScore\x1aJ\n" +
	"\x1cDeliveryTimePreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"X\n" +
	"\x17GetSystemMetricsRequest\x12=\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2\x1e.delivertrack.common.TimeRangeR\ttimeRange\"[\n" +
	"\x18GetSystemMetricsResponse\x12?\n" +
	"\ametrics\x18\x01 \x01(\v2%.delivertrack.analytics.SystemMetricsR\ametrics\"\xcc\x04\n" +
	"\rSystemMetrics\x12%\n" +
	"\x0eactive_drivers\x18\x01 \x01(\x05R\ractiveDrivers\x12+\n" +
	"\x11active_deliveries\x18\x02 \x01(\x05R\x10activeDeliveries\x12-\n" +
	"\x12pending_deliveries\x18\x03 \x01(\x05R\x11pendingDeliveries\x122\n" +
	"\x15average_response_time\x18\x04 \x01(\x01R\x13averageResponseTime\x12#\n" +
	"\rsystem_uptime\x18\x05 \x01(\x01R\fsystemUptime\x12%\n" +
	"\x0etotal_requests\x18\x06 \x01(\x03R\rtotalRequests\x12'\n" +
	"\x0ffailed_requests\x18\a \x01(\x03R\x0efailedRequests\x12\x1d\n" +
	"\n" +
	"error_rate\x18\b \x01(\x01R\terrorRate\x12`\n" +
	"\x0fapi_call_counts\x18\t \x03(\v28.delivertrack.analytics.SystemMetrics.ApiCallCountsEntryR\rapiCallCounts\x12L\n" +
	"\x0eresource_usage\x18\n" +
	" \x01(\v2%.delivertrack.analytics.ResourceUsageR\rresourceUsage\x1a@\n" +
	"\x12ApiCallCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xae\x01\n" +
	"\rResourceUsage\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x03 \x01(\x01R\tdiskUsage\x12\x1d\n" +
	"\n" +
	"network_in\x18\x04 \x01(\x03R\tnetworkIn\x12\x1f\n" +
	"\vnetwork_out\x18\x05 \x01(\x03R\n" +
	"networkOut\"\xfb\x02\n" +
	"\x15GenerateReportRequest\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".delivertrack.analytics.ReportTypeR\x04type\x12=\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2\x1e.delivertrack.common.TimeRangeR\ttimeRange\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12<\n" +
	"\x06format\x18\x04 \x01(\x0e2$.delivertrack.analytics.ReportFormatR\x06format\x12T\n" +
	"\afilters\x18\x05 \x03(\v2:.delivertrack.analytics.GenerateReportRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\x16GenerateReportResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12!\n" +
	"\fgenerated_at\x18\x03 \x01(\x03R\vgeneratedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"m\n" +
	"\x13GetDashboardRequest\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.delivertrack.analytics.DashboardTypeR\x04type\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\"W\n" +
	"\x14GetDashboardResponse\x12?\n" +
	"\tdashboard\x18\x01 \x01(\v2!.delivertrack.analytics.DashboardR\tdashboard\"\xb7\x02\n" +
	"\tDashboard\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12!\n" +
	"\flast_updated\x18\x02 \x01(\x03R\vlastUpdated\x12R\n" +
	"\x10delivery_summary\x18\x03 \x01(\v2'.delivertrack.analytics.DeliveryMetricsR\x0fdeliverySummary\x12/\n" +
	"\x04kpis\x18\x04 \x03(\v2\x1b.delivertrack.analytics.KPIR\x04kpis\x125\n" +
	"\x06charts\x18\x05 \x03(\v2\x1d.delivertrack.analytics.ChartR\x06charts\x125\n" +
	"\x06alerts\x18\x06 \x03(\v2\x1d.delivertrack.analytics.AlertR\x06alerts\"\xa5\x01\n" +
	"\x03KPI\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12+\n" +
	"\x11change_percentage\x18\x04 \x01(\x01R\x10changePercentage\x123\n" +
	"\x05trend\x18\x05 \x01(\x0e2\x1d.delivertrack.analytics.TrendR\x05trend\"\x91\x01\n" +
	"\x05Chart\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.delivertrack.analytics.ChartTypeR\x04type\x12;\n" +
	"\x04data\x18\x03 \x03(\v2'.delivertrack.analytics.TimeSeriesPointR\x04data\"\xd1\x01\n" +
	"\x0fTimeSeriesPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12N\n" +
	"\ametrics\x18\x03 \x03(\v24.delivertrack.analytics.TimeSeriesPoint.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xb7\x01\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\bseverity\x18\x02 \x01(\x0e2%.delivertrack.analytics.AlertSeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\"\n" +
	"\facknowledged\x18\x05 \x01(\bR\facknowledged\"w\n" +
	"\x19GetRouteEfficiencyRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12=\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2\x1e.delivertrack.common.TimeRangeR\ttimeRange\"e\n" +
	"\x1aGetRouteEfficiencyResponse\x12G\n" +
	"\n" +
	"efficiency\x18\x01 \x01(\v2'.delivertrack.analytics.RouteEfficiencyR\n" +
	"efficiency\"\xbd\x02\n" +
	"\x0fRouteEfficiency\x12%\n" +
	"\x0etotal_distance\x18\x01 \x01(\x01R\rtotalDistance\x12)\n" +
	"\x10optimal_distance\x18\x02 \x01(\x01R\x0foptimalDistance\x12)\n" +
	"\x10efficiency_score\x18\x03 \x01(\x01R\x0fefficiencyScore\x12#\n" +
	"\raverage_speed\x18\x04 \x01(\x01R\faverageSpeed\x12\x1f\n" +
	"\vtotal_stops\x18\x05 \x01(\x05R\n" +
	"totalStops\x12\x1b\n" +
	"\tidle_time\x18\x06 \x01(\x01R\bidleTime\x12!\n" +
	"\fdriving_time\x18\a \x01(\x01R\vdrivingTime\x12'\n" +
	"\x0ffuel_efficiency\x18\b \x01(\x01R\x0efuelEfficiency*\xad\x01\n" +
	"\x10AggregationLevel\x12!\n" +
	"\x1dAGGREGATION_LEVEL_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18AGGREGATION_LEVEL_HOURLY\x10\x01\x12\x1b\n" +
	"\x17AGGREGATION_LEVEL_DAILY\x10\x02\x12\x1c\n" +
	"\x18AGGREGATION_LEVEL_WEEKLY\x10\x03\x12\x1d\n" +
	"\x19AGGREGATION_LEVEL_MONTHLY\x10\x04*\xcb\x01\n" +
	"\n" +
	"ReportType\x12\x1b\n" +
	"\x17REPORT_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cREPORT_TYPE_DELIVERY_SUMMARY\x10\x01\x12\"\n" +
	"\x1eREPORT_TYPE_DRIVER_PERFORMANCE\x10\x02\x12\"\n" +
	"\x1eREPORT_TYPE_CUSTOMER_ANALYTICS\x10\x03\x12\x19\n" +
	"\x15REPORT_TYPE_FINANCIAL\x10\x04\x12\x1b\n" +
	"\x17REPORT_TYPE_OPERATIONAL\x10\x05*\x8c\x01\n" +
	"\fReportFormat\x12\x1d\n" +
	"\x19REPORT_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11REPORT_FORMAT_PDF\x10\x01\x12\x15\n" +
	"\x11REPORT_FORMAT_CSV\x10\x02\x12\x17\n" +
	"\x13REPORT_FORMAT_EXCEL\x10\x03\x12\x16\n" +
	"\x12REPORT_FORMAT_JSON\x10\x04*\xa4\x01\n" +
	"\rDashboardType\x12\x1e\n" +
	"\x1aDASHBOARD_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DASHBOARD_TYPE_OPERATIONS\x10\x01\x12\x19\n" +
	"\x15DASHBOARD_TYPE_DRIVER\x10\x02\x12\x1b\n" +
	"\x17DASHBOARD_TYPE_CUSTOMER\x10\x03\x12\x1c\n" +
	"\x18DASHBOARD_TYPE_EXECUTIVE\x10\x04*y\n" +
	"\tChartType\x12\x1a\n" +
	"\x16CHART_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCHART_TYPE_LINE\x10\x01\x12\x12\n" +
	"\x0eCHART_TYPE_BAR\x10\x02\x12\x12\n" +
	"\x0eCHART_TYPE_PIE\x10\x03\x12\x13\n" +
	"\x0fCHART_TYPE_AREA\x10\x04*N\n" +
	"\x05Trend\x12\x15\n" +
	"\x11TREND_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bTREND_UP\x10\x01\x12\x0e\n" +
	"\n" +
	"TREND_DOWN\x10\x02\x12\x10\n" +
	"\fTREND_STABLE\x10\x03*\x9b\x01\n" +
	"\rAlertSeverity\x12\x1e\n" +
	"\x1aALERT_SEVERITY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ALERT_SEVERITY_INFO\x10\x01\x12\x1a\n" +
	"\x16ALERT_SEVERITY_WARNING\x10\x02\x12\x18\n" +
	"\x14ALERT_SEVERITY_ERROR\x10\x03\x12\x1b\n" +
	"\x17ALERT_SEVERITY_CRITICAL\x10\x042\xc9\b\n" +
	"\x10AnalyticsService\x12f\n" +
	"\vRecordEvent\x12*.delivertrack.analytics.RecordEventRequest\x1a+.delivertrack.analytics.RecordEventResponse\x12x\n" +
	"\x11BatchRecordEvents\x120.delivertrack.analytics.BatchRecordEventsRequest\x1a1.delivertrack.analytics.BatchRecordEventsResponse\x12{\n" +
	"\x12GetDeliveryMetrics\x121.delivertrack.analytics.GetDeliveryMetricsRequest\x1a2.delivertrack.analytics.GetDeliveryMetricsResponse\x12\x81\x01\n" +
	"\x14GetDriverPerformance\x123.delivertrack.analytics.GetDriverPerformanceRequest\x1a4.delivertrack.analytics.GetDriverPerformanceResponse\x12\x81\x01\n" +
	"\x14GetCustomerAnalytics\x123.delivertrack.analytics.GetCustomerAnalyticsRequest\x1a4.delivertrack.analytics.GetCustomerAnalyticsResponse\x12u\n" +
	"\x10GetSystemMetrics\x12/.delivertrack.analytics.GetSystemMetricsRequest\x1a0.delivertrack.analytics.GetSystemMetricsResponse\x12o\n" +
	"\x0eGenerateReport\x12-.delivertrack.analytics.GenerateReportRequest\x1a..delivertrack.analytics.GenerateReportResponse\x12i\n" +
	"\fGetDashboard\x12+.delivertrack.analytics.GetDashboardRequest\x1a,.delivertrack.analytics.GetDashboardResponse\x12{\n" +
	"\x12GetRouteEfficiency\x121.delivertrack.analytics.GetRouteEfficiencyRequest\x1a2.delivertrack.analytics.GetRouteEfficiencyResponseB6Z4github.com/Keneke-Einar/delivertrack/proto/analyticsb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_analytics_proto_goTypes = []any{
	(AggregationLevel)(0),                // 0: delivertrack.analytics.AggregationLevel
	(ReportType)(0),                      // 1: delivertrack.analytics.ReportType
	(ReportFormat)(0),                    // 2: delivertrack.analytics.ReportFormat
	(DashboardType)(0),                   // 3: delivertrack.analytics.DashboardType
	(ChartType)(0),                       // 4: delivertrack.analytics.ChartType
	(Trend)(0),                           // 5: delivertrack.analytics.Trend
	(AlertSeverity)(0),                   // 6: delivertrack.analytics.AlertSeverity
	(*RecordEventRequest)(nil),           // 7: delivertrack.analytics.RecordEventRequest
	(*RecordEventResponse)(nil),          // 8: delivertrack.analytics.RecordEventResponse
	(*BatchRecordEventsRequest)(nil),     // 9: delivertrack.analytics.BatchRecordEventsRequest
	(*BatchRecordEventsResponse)(nil),    // 10: delivertrack.analytics.BatchRecordEventsResponse
	(*GetDeliveryMetricsRequest)(nil),    // 11: delivertrack.analytics.GetDeliveryMetricsRequest
	(*GetDeliveryMetricsResponse)(nil),   // 12: delivertrack.analytics.GetDeliveryMetricsResponse
	(*DeliveryMetrics)(nil),              // 13: delivertrack.analytics.DeliveryMetrics
	(*GetDriverPerformanceRequest)(nil),  // 14: delivertrack.analytics.GetDriverPerformanceRequest
	(*GetDriverPerformanceResponse)(nil), // 15: delivertrack.analytics.GetDriverPerformanceResponse
	(*DriverPerformance)(nil),            // 16: delivertrack.analytics.DriverPerformance
	(*GetCustomerAnalyticsRequest)(nil),  // 17: delivertrack.analytics.GetCustomerAnalyticsRequest
	(*GetCustomerAnalyticsResponse)(nil), // 18: delivertrack.analytics.GetCustomerAnalyticsResponse
	(*CustomerAnalytics)(nil),            // 19: delivertrack.analytics.CustomerAnalytics
	(*GetSystemMetricsRequest)(nil),      // 20: delivertrack.analytics.GetSystemMetricsRequest
	(*GetSystemMetricsResponse)(nil),     // 21: delivertrack.analytics.GetSystemMetricsResponse
	(*SystemMetrics)(nil),                // 22: delivertrack.analytics.SystemMetrics
	(*ResourceUsage)(nil),                // 23: delivertrack.analytics.ResourceUsage
	(*GenerateReportRequest)(nil),        // 24: delivertrack.analytics.GenerateReportRequest
	(*GenerateReportResponse)(nil),       // 25: delivertrack.analytics.GenerateReportResponse
	(*GetDashboardRequest)(nil),          // 26: delivertrack.analytics.GetDashboardRequest
	(*GetDashboardResponse)(nil),         // 27: delivertrack.analytics.GetDashboardResponse
	(*Dashboard)(nil),                    // 28: delivertrack.analytics.Dashboard
	(*KPI)(nil),                          // 29: delivertrack.analytics.KPI
	(*Chart)(nil),                        // 30: delivertrack.analytics.Chart
	(*TimeSeriesPoint)(nil),              // 31: delivertrack.analytics.TimeSeriesPoint
	(*Alert)(nil),                        // 32: delivertrack.analytics.Alert
	(*GetRouteEfficiencyRequest)(nil),    // 33: delivertrack.analytics.GetRouteEfficiencyRequest
	(*GetRouteEfficiencyResponse)(nil),   // 34: delivertrack.analytics.GetRouteEfficiencyResponse
	(*RouteEfficiency)(nil),              // 35: delivertrack.analytics.RouteEfficiency
	nil,                                  // 36: delivertrack.analytics.RecordEventRequest.PropertiesEntry
	nil,                                  // 37: delivertrack.analytics.CustomerAnalytics.DeliveryTimePreferencesEntry
	nil,                                  // 38: delivertrack.analytics.SystemMetrics.ApiCallCountsEntry
	nil,                                  // 39: delivertrack.analytics.GenerateReportRequest.FiltersEntry
	nil,                                  // 40: delivertrack.analytics.TimeSeriesPoint.MetricsEntry
	(*common.TimeRange)(nil),             // 41: delivertrack.common.TimeRange
	(*common.Location)(nil),              // 42: delivertrack.common.Location
}
var file_analytics_proto_depIdxs = []int32{
	36, // 0: delivertrack.analytics.RecordEventRequest.properties:type_name -> delivertrack.analytics.RecordEventRequest.PropertiesEntry
	7,  // 1: delivertrack.analytics.BatchRecordEventsRequest.events:type_name -> delivertrack.analytics.RecordEventRequest
	41, // 2: delivertrack.analytics.GetDeliveryMetricsRequest.time_range:type_name -> delivertrack.common.TimeRange
	0,  // 3: delivertrack.analytics.GetDeliveryMetricsRequest.aggregation:type_name -> delivertrack.analytics.AggregationLevel
	13, // 4: delivertrack.analytics.GetDeliveryMetricsResponse.metrics:type_name -> delivertrack.analytics.DeliveryMetrics
	31, // 5: delivertrack.analytics.GetDeliveryMetricsResponse.time_series:type_name -> delivertrack.analytics.TimeSeriesPoint
	41, // 6: delivertrack.analytics.GetDriverPerformanceRequest.time_range:type_name -> delivertrack.common.TimeRange
	16, // 7: delivertrack.analytics.GetDriverPerformanceResponse.performance:type_name -> delivertrack.analytics.DriverPerformance
	41, // 8: delivertrack.analytics.GetCustomerAnalyticsRequest.time_range:type_name -> delivertrack.common.TimeRange
	19, // 9: delivertrack.analytics.GetCustomerAnalyticsResponse.analytics:type_name -> delivertrack.analytics.CustomerAnalytics
	42, // 10: delivertrack.analytics.CustomerAnalytics.frequent_locations:type_name -> delivertrack.common.Location
	37, // 11: delivertrack.analytics.CustomerAnalytics.delivery_time_preferences:type_name -> delivertrack.analytics.CustomerAnalytics.DeliveryTimePreferencesEntry
	41, // 12: delivertrack.analytics.GetSystemMetricsRequest.time_range:type_name -> delivertrack.common.TimeRange
	22, // 13: delivertrack.analytics.GetSystemMetricsResponse.metrics:type_name -> delivertrack.analytics.SystemMetrics
	38, // 14: delivertrack.analytics.SystemMetrics.api_call_counts:type_name -> delivertrack.analytics.SystemMetrics.ApiCallCountsEntry
	23, // 15: delivertrack.analytics.SystemMetrics.resource_usage:type_name -> delivertrack.analytics.ResourceUsage
	1,  // 16: delivertrack.analytics.GenerateReportRequest.type:type_name -> delivertrack.analytics.ReportType
	41, // 17: delivertrack.analytics.GenerateReportRequest.time_range:type_name -> delivertrack.common.TimeRange
	2,  // 18: delivertrack.analytics.GenerateReportRequest.format:type_name -> delivertrack.analytics.ReportFormat
	39, // 19: delivertrack.analytics.GenerateReportRequest.filters:type_name -> delivertrack.analytics.GenerateReportRequest.FiltersEntry
	3,  // 20: delivertrack.analytics.GetDashboardRequest.type:type_name -> delivertrack.analytics.DashboardType
	28, // 21: delivertrack.analytics.GetDashboardResponse.dashboard:type_name -> delivertrack.analytics.Dashboard
	13, // 22: delivertrack.analytics.Dashboard.delivery_summary:type_name -> delivertrack.analytics.DeliveryMetrics
	29, // 23: delivertrack.analytics.Dashboard.kpis:type_name -> delivertrack.analytics.KPI
	30, // 24: delivertrack.analytics.Dashboard.charts:type_name -> delivertrack.analytics.Chart
	32, // 25: delivertrack.analytics.Dashboard.alerts:type_name -> delivertrack.analytics.Alert
	5,  // 26: delivertrack.analytics.KPI.trend:type_name -> delivertrack.analytics.Trend
	4,  // 27: delivertrack.analytics.Chart.type:type_name -> delivertrack.analytics.ChartType
	31, // 28: delivertrack.analytics.Chart.data:type_name -> delivertrack.analytics.TimeSeriesPoint
	40, // 29: delivertrack.analytics.TimeSeriesPoint.metrics:type_name -> delivertrack.analytics.TimeSeriesPoint.MetricsEntry
	6,  // 30: delivertrack.analytics.Alert.severity:type_name -> delivertrack.analytics.AlertSeverity
	41, // 31: delivertrack.analytics.GetRouteEfficiencyRequest.time_range:type_name -> delivertrack.common.TimeRange
	35, // 32: delivertrack.analytics.GetRouteEfficiencyResponse.efficiency:type_name -> delivertrack.analytics.RouteEfficiency
	7,  // 33: delivertrack.analytics.AnalyticsService.RecordEvent:input_type -> delivertrack.analytics.RecordEventRequest
	9,  // 34: delivertrack.analytics.AnalyticsService.BatchRecordEvents:input_type -> delivertrack.analytics.BatchRecordEventsRequest
	11, // 35: delivertrack.analytics.AnalyticsService.GetDeliveryMetrics:input_type -> delivertrack.analytics.GetDeliveryMetricsRequest
	14, // 36: delivertrack.analytics.AnalyticsService.GetDriverPerformance:input_type -> delivertrack.analytics.GetDriverPerformanceRequest
	17, // 37: delivertrack.analytics.AnalyticsService.GetCustomerAnalytics:input_type -> delivertrack.analytics.GetCustomerAnalyticsRequest
	20, // 38: delivertrack.analytics.AnalyticsService.GetSystemMetrics:input_type -> delivertrack.analytics.GetSystemMetricsRequest
	24, // 39: delivertrack.analytics.AnalyticsService.GenerateReport:input_type -> delivertrack.analytics.GenerateReportRequest
	26, // 40: delivertrack.analytics.AnalyticsService.GetDashboard:input_type -> delivertrack.analytics.GetDashboardRequest
	33, // 41: delivertrack.analytics.AnalyticsService.GetRouteEfficiency:input_type -> delivertrack.analytics.GetRouteEfficiencyRequest
	8,  // 42: delivertrack.analytics.AnalyticsService.RecordEvent:output_type -> delivertrack.analytics.RecordEventResponse
	10, // 43: delivertrack.analytics.AnalyticsService.BatchRecordEvents:output_type -> delivertrack.analytics.BatchRecordEventsResponse
	12, // 44: delivertrack.analytics.AnalyticsService.GetDeliveryMetrics:output_type -> delivertrack.analytics.GetDeliveryMetricsResponse
	15, // 45: delivertrack.analytics.AnalyticsService.GetDriverPerformance:output_type -> delivertrack.analytics.GetDriverPerformanceResponse
	18, // 46: delivertrack.analytics.AnalyticsService.GetCustomerAnalytics:output_type -> delivertrack.analytics.GetCustomerAnalyticsResponse
	21, // 47: delivertrack.analytics.AnalyticsService.GetSystemMetrics:output_type -> delivertrack.analytics.GetSystemMetricsResponse
	25, // 48: delivertrack.analytics.AnalyticsService.GenerateReport:output_type -> delivertrack.analytics.GenerateReportResponse
	27, // 49: delivertrack.analytics.AnalyticsService.GetDashboard:output_type -> delivertrack.analytics.GetDashboardResponse
	34, // 50: delivertrack.analytics.AnalyticsService.GetRouteEfficiency:output_type -> delivertrack.analytics.GetRouteEfficiencyResponse
	42, // [42:51] is the sub-list for method output_type
	33, // [33:42] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		EnumInfos:         file_analytics_proto_enumTypes,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
