// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: tracking.proto

package tracking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackingService_CreateTracking_FullMethodName       = "/delivertrack.tracking.TrackingService/CreateTracking"
	TrackingService_GetTracking_FullMethodName          = "/delivertrack.tracking.TrackingService/GetTracking"
	TrackingService_UpdateLocation_FullMethodName       = "/delivertrack.tracking.TrackingService/UpdateLocation"
	TrackingService_AddTrackingEvent_FullMethodName     = "/delivertrack.tracking.TrackingService/AddTrackingEvent"
	TrackingService_GetTrackingHistory_FullMethodName   = "/delivertrack.tracking.TrackingService/GetTrackingHistory"
	TrackingService_StreamLocation_FullMethodName       = "/delivertrack.tracking.TrackingService/StreamLocation"
	TrackingService_BatchUpdateLocations_FullMethodName = "/delivertrack.tracking.TrackingService/BatchUpdateLocations"
)

// TrackingServiceClient is the client API for TrackingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackingServiceClient interface {
	// Create a new tracking entry for a package
	CreateTracking(ctx context.Context, in *CreateTrackingRequest, opts ...grpc.CallOption) (*CreateTrackingResponse, error)
	// Get tracking information for a package
	GetTracking(ctx context.Context, in *GetTrackingRequest, opts ...grpc.CallOption) (*GetTrackingResponse, error)
	// Update location of a package
	UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error)
	// Add a tracking event
	AddTrackingEvent(ctx context.Context, in *AddTrackingEventRequest, opts ...grpc.CallOption) (*AddTrackingEventResponse, error)
	// Get tracking history
	GetTrackingHistory(ctx context.Context, in *GetTrackingHistoryRequest, opts ...grpc.CallOption) (*GetTrackingHistoryResponse, error)
	// Stream real-time location updates
	StreamLocation(ctx context.Context, in *StreamLocationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LocationUpdate], error)
	// Batch update locations
	BatchUpdateLocations(ctx context.Context, in *BatchUpdateLocationsRequest, opts ...grpc.CallOption) (*BatchUpdateLocationsResponse, error)
}

type trackingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackingServiceClient(cc grpc.ClientConnInterface) TrackingServiceClient {
	return &trackingServiceClient{cc}
}

func (c *trackingServiceClient) CreateTracking(ctx context.Context, in *CreateTrackingRequest, opts ...grpc.CallOption) (*CreateTrackingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTrackingResponse)
	err := c.cc.Invoke(ctx, TrackingService_CreateTracking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingServiceClient) GetTracking(ctx context.Context, in *GetTrackingRequest, opts ...grpc.CallOption) (*GetTrackingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackingResponse)
	err := c.cc.Invoke(ctx, TrackingService_GetTracking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingServiceClient) UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLocationResponse)
	err := c.cc.Invoke(ctx, TrackingService_UpdateLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingServiceClient) AddTrackingEvent(ctx context.Context, in *AddTrackingEventRequest, opts ...grpc.CallOption) (*AddTrackingEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTrackingEventResponse)
	err := c.cc.Invoke(ctx, TrackingService_AddTrackingEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingServiceClient) GetTrackingHistory(ctx context.Context, in *GetTrackingHistoryRequest, opts ...grpc.CallOption) (*GetTrackingHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackingHistoryResponse)
	err := c.cc.Invoke(ctx, TrackingService_GetTrackingHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingServiceClient) StreamLocation(ctx context.Context, in *StreamLocationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LocationUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrackingService_ServiceDesc.Streams[0], TrackingService_StreamLocation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLocationRequest, LocationUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrackingService_StreamLocationClient = grpc.ServerStreamingClient[LocationUpdate]

func (c *trackingServiceClient) BatchUpdateLocations(ctx context.Context, in *BatchUpdateLocationsRequest, opts ...grpc.CallOption) (*BatchUpdateLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpdateLocationsResponse)
	err := c.cc.Invoke(ctx, TrackingService_BatchUpdateLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackingServiceServer is the server API for TrackingService service.
// All implementations must embed UnimplementedTrackingServiceServer
// for forward compatibility.
type TrackingServiceServer interface {
	// Create a new tracking entry for a package
	CreateTracking(context.Context, *CreateTrackingRequest) (*CreateTrackingResponse, error)
	// Get tracking information for a package
	GetTracking(context.Context, *GetTrackingRequest) (*GetTrackingResponse, error)
	// Update location of a package
	UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationResponse, error)
	// Add a tracking event
	AddTrackingEvent(context.Context, *AddTrackingEventRequest) (*AddTrackingEventResponse, error)
	// Get tracking history
	GetTrackingHistory(context.Context, *GetTrackingHistoryRequest) (*GetTrackingHistoryResponse, error)
	// Stream real-time location updates
	StreamLocation(*StreamLocationRequest, grpc.ServerStreamingServer[LocationUpdate]) error
	// Batch update locations
	BatchUpdateLocations(context.Context, *BatchUpdateLocationsRequest) (*BatchUpdateLocationsResponse, error)
	mustEmbedUnimplementedTrackingServiceServer()
}

// UnimplementedTrackingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackingServiceServer struct{}

func (UnimplementedTrackingServiceServer) CreateTracking(context.Context, *CreateTrackingRequest) (*CreateTrackingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTracking not implemented")
}
func (UnimplementedTrackingServiceServer) GetTracking(context.Context, *GetTrackingRequest) (*GetTrackingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTracking not implemented")
}
func (UnimplementedTrackingServiceServer) UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLocation not implemented")
}
func (UnimplementedTrackingServiceServer) AddTrackingEvent(context.Context, *AddTrackingEventRequest) (*AddTrackingEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTrackingEvent not implemented")
}
func (UnimplementedTrackingServiceServer) GetTrackingHistory(context.Context, *GetTrackingHistoryRequest) (*GetTrackingHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrackingHistory not implemented")
}
func (UnimplementedTrackingServiceServer) StreamLocation(*StreamLocationRequest, grpc.ServerStreamingServer[LocationUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamLocation not implemented")
}
func (UnimplementedTrackingServiceServer) BatchUpdateLocations(context.Context, *BatchUpdateLocationsRequest) (*BatchUpdateLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUpdateLocations not implemented")
}
func (UnimplementedTrackingServiceServer) mustEmbedUnimplementedTrackingServiceServer() {}
func (UnimplementedTrackingServiceServer) testEmbeddedByValue()                         {}

// UnsafeTrackingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackingServiceServer will
// result in compilation errors.
type UnsafeTrackingServiceServer interface {
	mustEmbedUnimplementedTrackingServiceServer()
}

func RegisterTrackingServiceServer(s grpc.ServiceRegistrar, srv TrackingServiceServer) {
	// If the following call panics, it indicates UnimplementedTrackingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackingService_ServiceDesc, srv)
}

func _TrackingService_CreateTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServiceServer).CreateTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackingService_CreateTracking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServiceServer).CreateTracking(ctx, req.(*CreateTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingService_GetTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServiceServer).GetTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackingService_GetTracking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServiceServer).GetTracking(ctx, req.(*GetTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackingService_UpdateLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServiceServer).UpdateLocation(ctx, req.(*UpdateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingService_AddTrackingEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTrackingEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServiceServer).AddTrackingEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackingService_AddTrackingEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServiceServer).AddTrackingEvent(ctx, req.(*AddTrackingEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingService_GetTrackingHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackingHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServiceServer).GetTrackingHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackingService_GetTrackingHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServiceServer).GetTrackingHistory(ctx, req.(*GetTrackingHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingService_StreamLocation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLocationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrackingServiceServer).StreamLocation(m, &grpc.GenericServerStream[StreamLocationRequest, LocationUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrackingService_StreamLocationServer = grpc.ServerStreamingServer[LocationUpdate]

func _TrackingService_BatchUpdateLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServiceServer).BatchUpdateLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackingService_BatchUpdateLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServiceServer).BatchUpdateLocations(ctx, req.(*BatchUpdateLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackingService_ServiceDesc is the grpc.ServiceDesc for TrackingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delivertrack.tracking.TrackingService",
	HandlerType: (*TrackingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTracking",
			Handler:    _TrackingService_CreateTracking_Handler,
		},
		{
			MethodName: "GetTracking",
			Handler:    _TrackingService_GetTracking_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _TrackingService_UpdateLocation_Handler,
		},
		{
			MethodName: "AddTrackingEvent",
			Handler:    _TrackingService_AddTrackingEvent_Handler,
		},
		{
			MethodName: "GetTrackingHistory",
			Handler:    _TrackingService_GetTrackingHistory_Handler,
		},
		{
			MethodName: "BatchUpdateLocations",
			Handler:    _TrackingService_BatchUpdateLocations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLocation",
			Handler:       _TrackingService_StreamLocation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tracking.proto",
}
