// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tracking.proto

package tracking

import (
	common "github.com/Keneke-Einar/delivertrack/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackingStatus int32

const (
	TrackingStatus_TRACKING_STATUS_UNSPECIFIED      TrackingStatus = 0
	TrackingStatus_TRACKING_STATUS_CREATED          TrackingStatus = 1
	TrackingStatus_TRACKING_STATUS_PICKED_UP        TrackingStatus = 2
	TrackingStatus_TRACKING_STATUS_IN_TRANSIT       TrackingStatus = 3
	TrackingStatus_TRACKING_STATUS_OUT_FOR_DELIVERY TrackingStatus = 4
	TrackingStatus_TRACKING_STATUS_DELIVERED        TrackingStatus = 5
	TrackingStatus_TRACKING_STATUS_FAILED           TrackingStatus = 6
	TrackingStatus_TRACKING_STATUS_RETURNED         TrackingStatus = 7
)

// Enum value maps for TrackingStatus.
var (
	TrackingStatus_name = map[int32]string{
		0: "TRACKING_STATUS_UNSPECIFIED",
		1: "TRACKING_STATUS_CREATED",
		2: "TRACKING_STATUS_PICKED_UP",
		3: "TRACKING_STATUS_IN_TRANSIT",
		4: "TRACKING_STATUS_OUT_FOR_DELIVERY",
		5: "TRACKING_STATUS_DELIVERED",
		6: "TRACKING_STATUS_FAILED",
		7: "TRACKING_STATUS_RETURNED",
	}
	TrackingStatus_value = map[string]int32{
		"TRACKING_STATUS_UNSPECIFIED":      0,
		"TRACKING_STATUS_CREATED":          1,
		"TRACKING_STATUS_PICKED_UP":        2,
		"TRACKING_STATUS_IN_TRANSIT":       3,
		"TRACKING_STATUS_OUT_FOR_DELIVERY": 4,
		"TRACKING_STATUS_DELIVERED":        5,
		"TRACKING_STATUS_FAILED":           6,
		"TRACKING_STATUS_RETURNED":         7,
	}
)

func (x TrackingStatus) Enum() *TrackingStatus {
	p := new(TrackingStatus)
	*p = x
	return p
}

func (x TrackingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tracking_proto_enumTypes[0].Descriptor()
}

func (TrackingStatus) Type() protoreflect.EnumType {
	return &file_tracking_proto_enumTypes[0]
}

func (x TrackingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackingStatus.Descriptor instead.
func (TrackingStatus) EnumDescriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{0}
}

type CreateTrackingRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PackageId         string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	TrackingNumber    string                 `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Origin            *common.Location       `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination       *common.Location       `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	EstimatedDelivery int64                  `protobuf:"varint,5,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTrackingRequest) Reset() {
	*x = CreateTrackingRequest{}
	mi := &file_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackingRequest) ProtoMessage() {}

func (x *CreateTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackingRequest.ProtoReflect.Descriptor instead.
func (*CreateTrackingRequest) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTrackingRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *CreateTrackingRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *CreateTrackingRequest) GetOrigin() *common.Location {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *CreateTrackingRequest) GetDestination() *common.Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *CreateTrackingRequest) GetEstimatedDelivery() int64 {
	if x != nil {
		return x.EstimatedDelivery
	}
	return 0
}

type CreateTrackingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingId     string                 `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTrackingResponse) Reset() {
	*x = CreateTrackingResponse{}
	mi := &file_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackingResponse) ProtoMessage() {}

func (x *CreateTrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackingResponse.ProtoReflect.Descriptor instead.
func (*CreateTrackingResponse) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTrackingResponse) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *CreateTrackingResponse) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *CreateTrackingResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetTrackingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTrackingRequest) Reset() {
	*x = GetTrackingRequest{}
	mi := &file_tracking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingRequest) ProtoMessage() {}

func (x *GetTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingRequest.ProtoReflect.Descriptor instead.
func (*GetTrackingRequest) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{2}
}

func (x *GetTrackingRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

type GetTrackingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracking      *TrackingInfo          `protobuf:"bytes,1,opt,name=tracking,proto3" json:"tracking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackingResponse) Reset() {
	*x = GetTrackingResponse{}
	mi := &file_tracking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingResponse) ProtoMessage() {}

func (x *GetTrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingResponse.ProtoReflect.Descriptor instead.
func (*GetTrackingResponse) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{3}
}

func (x *GetTrackingResponse) GetTracking() *TrackingInfo {
	if x != nil {
		return x.Tracking
	}
	return nil
}

type TrackingInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TrackingId        string                 `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	TrackingNumber    string                 `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	PackageId         string                 `protobuf:"bytes,3,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	CurrentLocation   *common.Location       `protobuf:"bytes,4,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	Origin            *common.Location       `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination       *common.Location       `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	Status            TrackingStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=delivertrack.tracking.TrackingStatus" json:"status,omitempty"`
	EstimatedDelivery int64                  `protobuf:"varint,8,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	ActualDelivery    int64                  `protobuf:"varint,9,opt,name=actual_delivery,json=actualDelivery,proto3" json:"actual_delivery,omitempty"`
	Events            []*TrackingEvent       `protobuf:"bytes,10,rep,name=events,proto3" json:"events,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrackingInfo) Reset() {
	*x = TrackingInfo{}
	mi := &file_tracking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingInfo) ProtoMessage() {}

func (x *TrackingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingInfo.ProtoReflect.Descriptor instead.
func (*TrackingInfo) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{4}
}

func (x *TrackingInfo) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *TrackingInfo) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *TrackingInfo) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *TrackingInfo) GetCurrentLocation() *common.Location {
	if x != nil {
		return x.CurrentLocation
	}
	return nil
}

func (x *TrackingInfo) GetOrigin() *common.Location {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *TrackingInfo) GetDestination() *common.Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *TrackingInfo) GetStatus() TrackingStatus {
	if x != nil {
		return x.Status
	}
	return TrackingStatus_TRACKING_STATUS_UNSPECIFIED
}

func (x *TrackingInfo) GetEstimatedDelivery() int64 {
	if x != nil {
		return x.EstimatedDelivery
	}
	return 0
}

func (x *TrackingInfo) GetActualDelivery() int64 {
	if x != nil {
		return x.ActualDelivery
	}
	return 0
}

func (x *TrackingInfo) GetEvents() []*TrackingEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *TrackingInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TrackingInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type UpdateLocationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Location       *common.Location       `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_tracking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLocationRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *UpdateLocationRequest) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *UpdateLocationRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UpdateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationResponse) Reset() {
	*x = UpdateLocationResponse{}
	mi := &file_tracking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationResponse) ProtoMessage() {}

func (x *UpdateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateLocationResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AddTrackingEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	EventType      string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location       *common.Location       `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddTrackingEventRequest) Reset() {
	*x = AddTrackingEventRequest{}
	mi := &file_tracking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrackingEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrackingEventRequest) ProtoMessage() {}

func (x *AddTrackingEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrackingEventRequest.ProtoReflect.Descriptor instead.
func (*AddTrackingEventRequest) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{7}
}

func (x *AddTrackingEventRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *AddTrackingEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AddTrackingEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddTrackingEventRequest) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *AddTrackingEventRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AddTrackingEventRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AddTrackingEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrackingEventResponse) Reset() {
	*x = AddTrackingEventResponse{}
	mi := &file_tracking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrackingEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrackingEventResponse) ProtoMessage() {}

func (x *AddTrackingEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrackingEventResponse.ProtoReflect.Descriptor instead.
func (*AddTrackingEventResponse) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{8}
}

func (x *AddTrackingEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AddTrackingEventResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type TrackingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location      *common.Location       `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackingEvent) Reset() {
	*x = TrackingEvent{}
	mi := &file_tracking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingEvent) ProtoMessage() {}

func (x *TrackingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingEvent.ProtoReflect.Descriptor instead.
func (*TrackingEvent) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{9}
}

func (x *TrackingEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TrackingEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TrackingEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TrackingEvent) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *TrackingEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TrackingEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetTrackingHistoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	TimeRange      *common.TimeRange      `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTrackingHistoryRequest) Reset() {
	*x = GetTrackingHistoryRequest{}
	mi := &file_tracking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingHistoryRequest) ProtoMessage() {}

func (x *GetTrackingHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTrackingHistoryRequest) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{10}
}

func (x *GetTrackingHistoryRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *GetTrackingHistoryRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type GetTrackingHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TrackingEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackingHistoryResponse) Reset() {
	*x = GetTrackingHistoryResponse{}
	mi := &file_tracking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingHistoryResponse) ProtoMessage() {}

func (x *GetTrackingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTrackingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{11}
}

func (x *GetTrackingHistoryResponse) GetEvents() []*TrackingEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type StreamLocationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamLocationRequest) Reset() {
	*x = StreamLocationRequest{}
	mi := &file_tracking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLocationRequest) ProtoMessage() {}

func (x *StreamLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLocationRequest.ProtoReflect.Descriptor instead.
func (*StreamLocationRequest) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{12}
}

func (x *StreamLocationRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

type LocationUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Location       *common.Location       `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Speed          float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`     // km/h
	Bearing        float64                `protobuf:"fixed64,5,opt,name=bearing,proto3" json:"bearing,omitempty"` // degrees
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocationUpdate) Reset() {
	*x = LocationUpdate{}
	mi := &file_tracking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUpdate) ProtoMessage() {}

func (x *LocationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUpdate.ProtoReflect.Descriptor instead.
func (*LocationUpdate) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{13}
}

func (x *LocationUpdate) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *LocationUpdate) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *LocationUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LocationUpdate) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *LocationUpdate) GetBearing() float64 {
	if x != nil {
		return x.Bearing
	}
	return 0
}

type BatchUpdateLocationsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Updates       []*UpdateLocationRequest `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateLocationsRequest) Reset() {
	*x = BatchUpdateLocationsRequest{}
	mi := &file_tracking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateLocationsRequest) ProtoMessage() {}

func (x *BatchUpdateLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateLocationsRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateLocationsRequest) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{14}
}

func (x *BatchUpdateLocationsRequest) GetUpdates() []*UpdateLocationRequest {
	if x != nil {
		return x.Updates
	}
	return nil
}

type BatchUpdateLocationsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount          int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount           int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	FailedTrackingNumbers []string               `protobuf:"bytes,3,rep,name=failed_tracking_numbers,json=failedTrackingNumbers,proto3" json:"failed_tracking_numbers,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BatchUpdateLocationsResponse) Reset() {
	*x = BatchUpdateLocationsResponse{}
	mi := &file_tracking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateLocationsResponse) ProtoMessage() {}

func (x *BatchUpdateLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateLocationsResponse.ProtoReflect.Descriptor instead.
func (*BatchUpdateLocationsResponse) Descriptor() ([]byte, []int) {
	return file_tracking_proto_rawDescGZIP(), []int{15}
}

func (x *BatchUpdateLocationsResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchUpdateLocationsResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *BatchUpdateLocationsResponse) GetFailedTrackingNumbers() []string {
	if x != nil {
		return x.FailedTrackingNumbers
	}
	return nil
}

var File_tracking_proto protoreflect.FileDescriptor

const file_tracking_proto_rawDesc = "" +
	"\n" +
	"\x0etracking.proto\x12\x15delivertrack.tracking\x1a\fcommon.proto\"\x86\x02\n" +
	"\x15CreateTrackingRequest\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12'\n" +
	"\x0ftracking_number\x18\x02 \x01(\tR\x0etrackingNumber\x125\n" +
	"\x06origin\x18\x03 \x01(\v2\x1d.delivertrack.common.LocationR\x06origin\x12?\n" +
	"\vdestination\x18\x04 \x01(\v2\x1d.delivertrack.common.LocationR\vdestination\x12-\n" +
	"\x12estimated_delivery\x18\x05 \x01(\x03R\x11estimatedDelivery\"\x81\x01\n" +
	"\x16CreateTrackingResponse\x12\x1f\n" +
	"\vtracking_id\x18\x01 \x01(\tR\n" +
	"trackingId\x12'\n" +
	"\x0ftracking_number\x18\x02 \x01(\tR\x0etrackingNumber\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"=\n" +
	"\x12GetTrackingRequest\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\"V\n" +
	"\x13GetTrackingResponse\x12?\n" +
	"\btracking\x18\x01 \x01(\v2#.delivertrack.tracking.TrackingInfoR\btracking\"\xcc\x04\n" +
	"\fTrackingInfo\x12\x1f\n" +
	"\vtracking_id\x18\x01 \x01(\tR\n" +
	"trackingId\x12'\n" +
	"\x0ftracking_number\x18\x02 \x01(\tR\x0etrackingNumber\x12\x1d\n" +
	"\n" +
	"package_id\x18\x03 \x01(\tR\tpackageId\x12H\n" +
	"\x10current_location\x18\x04 \x01(\v2\x1d.delivertrack.common.LocationR\x0fcurrentLocation\x125\n" +
	"\x06origin\x18\x05 \x01(\v2\x1d.delivertrack.common.LocationR\x06origin\x12?\n" +
	"\vdestination\x18\x06 \x01(\v2\x1d.delivertrack.common.LocationR\vdestination\x12=\n" +
	"\x06status\x18\a \x01(\x0e2%.delivertrack.tracking.TrackingStatusR\x06status\x12-\n" +
	"\x12estimated_delivery\x18\b \x01(\x03R\x11estimatedDelivery\x12'\n" +
	"\x0factual_delivery\x18\t \x01(\x03R\x0eactualDelivery\x12<\n" +
	"\x06events\x18\n" +
	" \x03(\v2$.delivertrack.tracking.TrackingEventR\x06events\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\"\x99\x01\n" +
	"\x15UpdateLocationRequest\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\x129\n" +
	"\blocation\x18\x02 \x01(\v2\x1d.delivertrack.common.LocationR\blocation\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"Q\n" +
	"\x16UpdateLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\x03R\tupdatedAt\"\xf3\x02\n" +
	"\x17AddTrackingEventRequest\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\blocation\x18\x04 \x01(\v2\x1d.delivertrack.common.LocationR\blocation\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12X\n" +
	"\bmetadata\x18\x06 \x03(\v2<.delivertrack.tracking.AddTrackingEventRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x18AddTrackingEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\"\xd1\x02\n" +
	"\rTrackingEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\blocation\x18\x04 \x01(\v2\x1d.delivertrack.common.LocationR\blocation\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12N\n" +
	"\bmetadata\x18\x06 \x03(\v22.delivertrack.tracking.TrackingEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x19GetTrackingHistoryRequest\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\x12=\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2\x1e.delivertrack.common.TimeRangeR\ttimeRange\"Z\n" +
	"\x1aGetTrackingHistoryResponse\x12<\n" +
	"\x06events\x18\x01 \x03(\v2$.delivertrack.tracking.TrackingEventR\x06events\"@\n" +
	"\x15StreamLocationRequest\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\"\xc2\x01\n" +
	"\x0eLocationUpdate\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\x129\n" +
	"\blocation\x18\x02 \x01(\v2\x1d.delivertrack.common.LocationR\blocation\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\x12\x18\n" +
	"\abearing\x18\x05 \x01(\x01R\abearing\"e\n" +
	"\x1bBatchUpdateLocationsRequest\x12F\n" +
	"\aupdates\x18\x01 \x03(\v2,.delivertrack.tracking.UpdateLocationRequestR\aupdates\"\x9e\x01\n" +
	"\x1cBatchUpdateLocationsResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x126\n" +
	"\x17failed_tracking_numbers\x18\x03 \x03(\tR\x15failedTrackingNumbers*\x8c\x02\n" +
	"\x0eTrackingStatus\x12\x1f\n" +
	"\x1bTRACKING_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRACKING_STATUS_CREATED\x10\x01\x12\x1d\n" +
	"\x19TRACKING_STATUS_PICKED_UP\x10\x02\x12\x1e\n" +
	"\x1aTRACKING_STATUS_IN_TRANSIT\x10\x03\x12$\n" +
	" TRACKING_STATUS_OUT_FOR_DELIVERY\x10\x04\x12\x1d\n" +
	"\x19TRACKING_STATUS_DELIVERED\x10\x05\x12\x1a\n" +
	"\x16TRACKING_STATUS_FAILED\x10\x06\x12\x1c\n" +
	"\x18TRACKING_STATUS_RETURNED\x10\a2\xaf\x06\n" +
	"\x0fTrackingService\x12m\n" +
	"\x0eCreateTracking\x12,.delivertrack.tracking.CreateTrackingRequest\x1a-.delivertrack.tracking.CreateTrackingResponse\x12d\n" +
	"\vGetTracking\x12).delivertrack.tracking.GetTrackingRequest\x1a*.delivertrack.tracking.GetTrackingResponse\x12m\n" +
	"\x0eUpdateLocation\x12,.delivertrack.tracking.UpdateLocationRequest\x1a-.delivertrack.tracking.UpdateLocationResponse\x12s\n" +
	"\x10AddTrackingEvent\x12..delivertrack.tracking.AddTrackingEventRequest\x1a/.delivertrack.tracking.AddTrackingEventResponse\x12y\n" +
	"\x12GetTrackingHistory\x120.delivertrack.tracking.GetTrackingHistoryRequest\x1a1.delivertrack.tracking.GetTrackingHistoryResponse\x12g\n" +
	"\x0eStreamLocation\x12,.delivertrack.tracking.StreamLocationRequest\x1a%.delivertrack.tracking.LocationUpdate0\x01\x12\x7f\n" +
	"\x14BatchUpdateLocations\x122.delivertrack.tracking.BatchUpdateLocationsRequest\x1a3.delivertrack.tracking.BatchUpdateLocationsResponseB5Z3github.com/Keneke-Einar/delivertrack/proto/trackingb\x06proto3"

var (
	file_tracking_proto_rawDescOnce sync.Once
	file_tracking_proto_rawDescData []byte
)

func file_tracking_proto_rawDescGZIP() []byte {
	file_tracking_proto_rawDescOnce.Do(func() {
		file_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracking_proto_rawDesc), len(file_tracking_proto_rawDesc)))
	})
	return file_tracking_proto_rawDescData
}

var file_tracking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_tracking_proto_goTypes = []any{
	(TrackingStatus)(0),                  // 0: delivertrack.tracking.TrackingStatus
	(*CreateTrackingRequest)(nil),        // 1: delivertrack.tracking.CreateTrackingRequest
	(*CreateTrackingResponse)(nil),       // 2: delivertrack.tracking.CreateTrackingResponse
	(*GetTrackingRequest)(nil),           // 3: delivertrack.tracking.GetTrackingRequest
	(*GetTrackingResponse)(nil),          // 4: delivertrack.tracking.GetTrackingResponse
	(*TrackingInfo)(nil),                 // 5: delivertrack.tracking.TrackingInfo
	(*UpdateLocationRequest)(nil),        // 6: delivertrack.tracking.UpdateLocationRequest
	(*UpdateLocationResponse)(nil),       // 7: delivertrack.tracking.UpdateLocationResponse
	(*AddTrackingEventRequest)(nil),      // 8: delivertrack.tracking.AddTrackingEventRequest
	(*AddTrackingEventResponse)(nil),     // 9: delivertrack.tracking.AddTrackingEventResponse
	(*TrackingEvent)(nil),                // 10: delivertrack.tracking.TrackingEvent
	(*GetTrackingHistoryRequest)(nil),    // 11: delivertrack.tracking.GetTrackingHistoryRequest
	(*GetTrackingHistoryResponse)(nil),   // 12: delivertrack.tracking.GetTrackingHistoryResponse
	(*StreamLocationRequest)(nil),        // 13: delivertrack.tracking.StreamLocationRequest
	(*LocationUpdate)(nil),               // 14: delivertrack.tracking.LocationUpdate
	(*BatchUpdateLocationsRequest)(nil),  // 15: delivertrack.tracking.BatchUpdateLocationsRequest
	(*BatchUpdateLocationsResponse)(nil), // 16: delivertrack.tracking.BatchUpdateLocationsResponse
	nil,                                  // 17: delivertrack.tracking.AddTrackingEventRequest.MetadataEntry
	nil,                                  // 18: delivertrack.tracking.TrackingEvent.MetadataEntry
	(*common.Location)(nil),              // 19: delivertrack.common.Location
	(*common.TimeRange)(nil),             // 20: delivertrack.common.TimeRange
}
var file_tracking_proto_depIdxs = []int32{
	19, // 0: delivertrack.tracking.CreateTrackingRequest.origin:type_name -> delivertrack.common.Location
	19, // 1: delivertrack.tracking.CreateTrackingRequest.destination:type_name -> delivertrack.common.Location
	5,  // 2: delivertrack.tracking.GetTrackingResponse.tracking:type_name -> delivertrack.tracking.TrackingInfo
	19, // 3: delivertrack.tracking.TrackingInfo.current_location:type_name -> delivertrack.common.Location
	19, // 4: delivertrack.tracking.TrackingInfo.origin:type_name -> delivertrack.common.Location
	19, // 5: delivertrack.tracking.TrackingInfo.destination:type_name -> delivertrack.common.Location
	0,  // 6: delivertrack.tracking.TrackingInfo.status:type_name -> delivertrack.tracking.TrackingStatus
	10, // 7: delivertrack.tracking.TrackingInfo.events:type_name -> delivertrack.tracking.TrackingEvent
	19, // 8: delivertrack.tracking.UpdateLocationRequest.location:type_name -> delivertrack.common.Location
	19, // 9: delivertrack.tracking.AddTrackingEventRequest.location:type_name -> delivertrack.common.Location
	17, // 10: delivertrack.tracking.AddTrackingEventRequest.metadata:type_name -> delivertrack.tracking.AddTrackingEventRequest.MetadataEntry
	19, // 11: delivertrack.tracking.TrackingEvent.location:type_name -> delivertrack.common.Location
	18, // 12: delivertrack.tracking.TrackingEvent.metadata:type_name -> delivertrack.tracking.TrackingEvent.MetadataEntry
	20, // 13: delivertrack.tracking.GetTrackingHistoryRequest.time_range:type_name -> delivertrack.common.TimeRange
	10, // 14: delivertrack.tracking.GetTrackingHistoryResponse.events:type_name -> delivertrack.tracking.TrackingEvent
	19, // 15: delivertrack.tracking.LocationUpdate.location:type_name -> delivertrack.common.Location
	6,  // 16: delivertrack.tracking.BatchUpdateLocationsRequest.updates:type_name -> delivertrack.tracking.UpdateLocationRequest
	1,  // 17: delivertrack.tracking.TrackingService.CreateTracking:input_type -> delivertrack.tracking.CreateTrackingRequest
	3,  // 18: delivertrack.tracking.TrackingService.GetTracking:input_type -> delivertrack.tracking.GetTrackingRequest
	6,  // 19: delivertrack.tracking.TrackingService.UpdateLocation:input_type -> delivertrack.tracking.UpdateLocationRequest
	8,  // 20: delivertrack.tracking.TrackingService.AddTrackingEvent:input_type -> delivertrack.tracking.AddTrackingEventRequest
	11, // 21: delivertrack.tracking.TrackingService.GetTrackingHistory:input_type -> delivertrack.tracking.GetTrackingHistoryRequest
	13, // 22: delivertrack.tracking.TrackingService.StreamLocation:input_type -> delivertrack.tracking.StreamLocationRequest
	15, // 23: delivertrack.tracking.TrackingService.BatchUpdateLocations:input_type -> delivertrack.tracking.BatchUpdateLocationsRequest
	2,  // 24: delivertrack.tracking.TrackingService.CreateTracking:output_type -> delivertrack.tracking.CreateTrackingResponse
	4,  // 25: delivertrack.tracking.TrackingService.GetTracking:output_type -> delivertrack.tracking.GetTrackingResponse
	7,  // 26: delivertrack.tracking.TrackingService.UpdateLocation:output_type -> delivertrack.tracking.UpdateLocationResponse
	9,  // 27: delivertrack.tracking.TrackingService.AddTrackingEvent:output_type -> delivertrack.tracking.AddTrackingEventResponse
	12, // 28: delivertrack.tracking.TrackingService.GetTrackingHistory:output_type -> delivertrack.tracking.GetTrackingHistoryResponse
	14, // 29: delivertrack.tracking.TrackingService.StreamLocation:output_type -> delivertrack.tracking.LocationUpdate
	16, // 30: delivertrack.tracking.TrackingService.BatchUpdateLocations:output_type -> delivertrack.tracking.BatchUpdateLocationsResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_tracking_proto_init() }
func file_tracking_proto_init() {
	if File_tracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracking_proto_rawDesc), len(file_tracking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracking_proto_goTypes,
		DependencyIndexes: file_tracking_proto_depIdxs,
		EnumInfos:         file_tracking_proto_enumTypes,
		MessageInfos:      file_tracking_proto_msgTypes,
	}.Build()
	File_tracking_proto = out.File
	file_tracking_proto_goTypes = nil
	file_tracking_proto_depIdxs = nil
}
