// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: delivery.proto

package delivery

import (
	common "github.com/Keneke-Einar/delivertrack/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED      DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_PENDING          DeliveryStatus = 1
	DeliveryStatus_DELIVERY_STATUS_ASSIGNED         DeliveryStatus = 2
	DeliveryStatus_DELIVERY_STATUS_PICKED_UP        DeliveryStatus = 3
	DeliveryStatus_DELIVERY_STATUS_IN_TRANSIT       DeliveryStatus = 4
	DeliveryStatus_DELIVERY_STATUS_OUT_FOR_DELIVERY DeliveryStatus = 5
	DeliveryStatus_DELIVERY_STATUS_DELIVERED        DeliveryStatus = 6
	DeliveryStatus_DELIVERY_STATUS_FAILED           DeliveryStatus = 7
	DeliveryStatus_DELIVERY_STATUS_CANCELLED        DeliveryStatus = 8
	DeliveryStatus_DELIVERY_STATUS_RETURNED         DeliveryStatus = 9
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_PENDING",
		2: "DELIVERY_STATUS_ASSIGNED",
		3: "DELIVERY_STATUS_PICKED_UP",
		4: "DELIVERY_STATUS_IN_TRANSIT",
		5: "DELIVERY_STATUS_OUT_FOR_DELIVERY",
		6: "DELIVERY_STATUS_DELIVERED",
		7: "DELIVERY_STATUS_FAILED",
		8: "DELIVERY_STATUS_CANCELLED",
		9: "DELIVERY_STATUS_RETURNED",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED":      0,
		"DELIVERY_STATUS_PENDING":          1,
		"DELIVERY_STATUS_ASSIGNED":         2,
		"DELIVERY_STATUS_PICKED_UP":        3,
		"DELIVERY_STATUS_IN_TRANSIT":       4,
		"DELIVERY_STATUS_OUT_FOR_DELIVERY": 5,
		"DELIVERY_STATUS_DELIVERED":        6,
		"DELIVERY_STATUS_FAILED":           7,
		"DELIVERY_STATUS_CANCELLED":        8,
		"DELIVERY_STATUS_RETURNED":         9,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_proto_enumTypes[0].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_delivery_proto_enumTypes[0]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{0}
}

type DeliveryPriority int32

const (
	DeliveryPriority_PRIORITY_UNSPECIFIED DeliveryPriority = 0
	DeliveryPriority_PRIORITY_STANDARD    DeliveryPriority = 1
	DeliveryPriority_PRIORITY_EXPRESS     DeliveryPriority = 2
	DeliveryPriority_PRIORITY_SAME_DAY    DeliveryPriority = 3
	DeliveryPriority_PRIORITY_URGENT      DeliveryPriority = 4
)

// Enum value maps for DeliveryPriority.
var (
	DeliveryPriority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_STANDARD",
		2: "PRIORITY_EXPRESS",
		3: "PRIORITY_SAME_DAY",
		4: "PRIORITY_URGENT",
	}
	DeliveryPriority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_STANDARD":    1,
		"PRIORITY_EXPRESS":     2,
		"PRIORITY_SAME_DAY":    3,
		"PRIORITY_URGENT":      4,
	}
)

func (x DeliveryPriority) Enum() *DeliveryPriority {
	p := new(DeliveryPriority)
	*p = x
	return p
}

func (x DeliveryPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_proto_enumTypes[1].Descriptor()
}

func (DeliveryPriority) Type() protoreflect.EnumType {
	return &file_delivery_proto_enumTypes[1]
}

func (x DeliveryPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryPriority.Descriptor instead.
func (DeliveryPriority) EnumDescriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{1}
}

type CreateDeliveryRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PackageId           string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	CustomerId          string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PickupLocation      *common.Location       `protobuf:"bytes,3,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	DeliveryLocation    *common.Location       `protobuf:"bytes,4,opt,name=delivery_location,json=deliveryLocation,proto3" json:"delivery_location,omitempty"`
	ScheduledPickup     int64                  `protobuf:"varint,5,opt,name=scheduled_pickup,json=scheduledPickup,proto3" json:"scheduled_pickup,omitempty"`
	ScheduledDelivery   int64                  `protobuf:"varint,6,opt,name=scheduled_delivery,json=scheduledDelivery,proto3" json:"scheduled_delivery,omitempty"`
	Priority            DeliveryPriority       `protobuf:"varint,7,opt,name=priority,proto3,enum=delivertrack.delivery.DeliveryPriority" json:"priority,omitempty"`
	PackageDetails      *PackageDetails        `protobuf:"bytes,8,opt,name=package_details,json=packageDetails,proto3" json:"package_details,omitempty"`
	SpecialInstructions string                 `protobuf:"bytes,9,opt,name=special_instructions,json=specialInstructions,proto3" json:"special_instructions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateDeliveryRequest) Reset() {
	*x = CreateDeliveryRequest{}
	mi := &file_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeliveryRequest) ProtoMessage() {}

func (x *CreateDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeliveryRequest.ProtoReflect.Descriptor instead.
func (*CreateDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDeliveryRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *CreateDeliveryRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateDeliveryRequest) GetPickupLocation() *common.Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *CreateDeliveryRequest) GetDeliveryLocation() *common.Location {
	if x != nil {
		return x.DeliveryLocation
	}
	return nil
}

func (x *CreateDeliveryRequest) GetScheduledPickup() int64 {
	if x != nil {
		return x.ScheduledPickup
	}
	return 0
}

func (x *CreateDeliveryRequest) GetScheduledDelivery() int64 {
	if x != nil {
		return x.ScheduledDelivery
	}
	return 0
}

func (x *CreateDeliveryRequest) GetPriority() DeliveryPriority {
	if x != nil {
		return x.Priority
	}
	return DeliveryPriority_PRIORITY_UNSPECIFIED
}

func (x *CreateDeliveryRequest) GetPackageDetails() *PackageDetails {
	if x != nil {
		return x.PackageDetails
	}
	return nil
}

func (x *CreateDeliveryRequest) GetSpecialInstructions() string {
	if x != nil {
		return x.SpecialInstructions
	}
	return ""
}

type CreateDeliveryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId     string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDeliveryResponse) Reset() {
	*x = CreateDeliveryResponse{}
	mi := &file_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeliveryResponse) ProtoMessage() {}

func (x *CreateDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeliveryResponse.ProtoReflect.Descriptor instead.
func (*CreateDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDeliveryResponse) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *CreateDeliveryResponse) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *CreateDeliveryResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryRequest) Reset() {
	*x = GetDeliveryRequest{}
	mi := &file_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryRequest) ProtoMessage() {}

func (x *GetDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeliveryRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

type GetDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *Delivery              `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryResponse) Reset() {
	*x = GetDeliveryResponse{}
	mi := &file_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryResponse) ProtoMessage() {}

func (x *GetDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeliveryResponse) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type Delivery struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId          string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	PackageId           string                 `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	CustomerId          string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	DriverId            string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TrackingNumber      string                 `protobuf:"bytes,5,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	PickupLocation      *common.Location       `protobuf:"bytes,6,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	DeliveryLocation    *common.Location       `protobuf:"bytes,7,opt,name=delivery_location,json=deliveryLocation,proto3" json:"delivery_location,omitempty"`
	Status              DeliveryStatus         `protobuf:"varint,8,opt,name=status,proto3,enum=delivertrack.delivery.DeliveryStatus" json:"status,omitempty"`
	ScheduledPickup     int64                  `protobuf:"varint,9,opt,name=scheduled_pickup,json=scheduledPickup,proto3" json:"scheduled_pickup,omitempty"`
	ScheduledDelivery   int64                  `protobuf:"varint,10,opt,name=scheduled_delivery,json=scheduledDelivery,proto3" json:"scheduled_delivery,omitempty"`
	ActualPickup        int64                  `protobuf:"varint,11,opt,name=actual_pickup,json=actualPickup,proto3" json:"actual_pickup,omitempty"`
	ActualDelivery      int64                  `protobuf:"varint,12,opt,name=actual_delivery,json=actualDelivery,proto3" json:"actual_delivery,omitempty"`
	Priority            DeliveryPriority       `protobuf:"varint,13,opt,name=priority,proto3,enum=delivertrack.delivery.DeliveryPriority" json:"priority,omitempty"`
	PackageDetails      *PackageDetails        `protobuf:"bytes,14,opt,name=package_details,json=packageDetails,proto3" json:"package_details,omitempty"`
	SpecialInstructions string                 `protobuf:"bytes,15,opt,name=special_instructions,json=specialInstructions,proto3" json:"special_instructions,omitempty"`
	SignatureUrl        string                 `protobuf:"bytes,16,opt,name=signature_url,json=signatureUrl,proto3" json:"signature_url,omitempty"`
	PhotoUrls           []string               `protobuf:"bytes,17,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	CreatedAt           int64                  `protobuf:"varint,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           int64                  `protobuf:"varint,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *Delivery) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *Delivery) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *Delivery) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Delivery) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Delivery) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *Delivery) GetPickupLocation() *common.Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *Delivery) GetDeliveryLocation() *common.Location {
	if x != nil {
		return x.DeliveryLocation
	}
	return nil
}

func (x *Delivery) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *Delivery) GetScheduledPickup() int64 {
	if x != nil {
		return x.ScheduledPickup
	}
	return 0
}

func (x *Delivery) GetScheduledDelivery() int64 {
	if x != nil {
		return x.ScheduledDelivery
	}
	return 0
}

func (x *Delivery) GetActualPickup() int64 {
	if x != nil {
		return x.ActualPickup
	}
	return 0
}

func (x *Delivery) GetActualDelivery() int64 {
	if x != nil {
		return x.ActualDelivery
	}
	return 0
}

func (x *Delivery) GetPriority() DeliveryPriority {
	if x != nil {
		return x.Priority
	}
	return DeliveryPriority_PRIORITY_UNSPECIFIED
}

func (x *Delivery) GetPackageDetails() *PackageDetails {
	if x != nil {
		return x.PackageDetails
	}
	return nil
}

func (x *Delivery) GetSpecialInstructions() string {
	if x != nil {
		return x.SpecialInstructions
	}
	return ""
}

func (x *Delivery) GetSignatureUrl() string {
	if x != nil {
		return x.SignatureUrl
	}
	return ""
}

func (x *Delivery) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

func (x *Delivery) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Delivery) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type UpdateDeliveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Status        DeliveryStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=delivertrack.delivery.DeliveryStatus" json:"status,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	Location      *common.Location       `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryStatusRequest) Reset() {
	*x = UpdateDeliveryStatusRequest{}
	mi := &file_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryStatusRequest) ProtoMessage() {}

func (x *UpdateDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDeliveryStatusRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *UpdateDeliveryStatusRequest) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *UpdateDeliveryStatusRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *UpdateDeliveryStatusRequest) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type UpdateDeliveryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryStatusResponse) Reset() {
	*x = UpdateDeliveryStatusResponse{}
	mi := &file_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryStatusResponse) ProtoMessage() {}

func (x *UpdateDeliveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDeliveryStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDeliveryStatusResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AssignDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDriverRequest) Reset() {
	*x = AssignDriverRequest{}
	mi := &file_delivery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDriverRequest) ProtoMessage() {}

func (x *AssignDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDriverRequest.ProtoReflect.Descriptor instead.
func (*AssignDriverRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{7}
}

func (x *AssignDriverRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *AssignDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type AssignDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AssignedAt    int64                  `protobuf:"varint,2,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDriverResponse) Reset() {
	*x = AssignDriverResponse{}
	mi := &file_delivery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDriverResponse) ProtoMessage() {}

func (x *AssignDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDriverResponse.ProtoReflect.Descriptor instead.
func (*AssignDriverResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{8}
}

func (x *AssignDriverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignDriverResponse) GetAssignedAt() int64 {
	if x != nil {
		return x.AssignedAt
	}
	return 0
}

type ListDeliveriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        DeliveryStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=delivertrack.delivery.DeliveryStatus" json:"status,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	TimeRange     *common.TimeRange      `protobuf:"bytes,4,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesRequest) Reset() {
	*x = ListDeliveriesRequest{}
	mi := &file_delivery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveriesRequest) ProtoMessage() {}

func (x *ListDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveriesRequest.ProtoReflect.Descriptor instead.
func (*ListDeliveriesRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{9}
}

func (x *ListDeliveriesRequest) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *ListDeliveriesRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ListDeliveriesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListDeliveriesRequest) GetTimeRange() *common.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *ListDeliveriesRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListDeliveriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*Delivery            `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesResponse) Reset() {
	*x = ListDeliveriesResponse{}
	mi := &file_delivery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveriesResponse) ProtoMessage() {}

func (x *ListDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveriesResponse.ProtoReflect.Descriptor instead.
func (*ListDeliveriesResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{10}
}

func (x *ListDeliveriesResponse) GetDeliveries() []*Delivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *ListDeliveriesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListDeliveriesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDeliveriesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CancelDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDeliveryRequest) Reset() {
	*x = CancelDeliveryRequest{}
	mi := &file_delivery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDeliveryRequest) ProtoMessage() {}

func (x *CancelDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDeliveryRequest.ProtoReflect.Descriptor instead.
func (*CancelDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{11}
}

func (x *CancelDeliveryRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *CancelDeliveryRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CancelledAt   int64                  `protobuf:"varint,2,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDeliveryResponse) Reset() {
	*x = CancelDeliveryResponse{}
	mi := &file_delivery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDeliveryResponse) ProtoMessage() {}

func (x *CancelDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDeliveryResponse.ProtoReflect.Descriptor instead.
func (*CancelDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{12}
}

func (x *CancelDeliveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelDeliveryResponse) GetCancelledAt() int64 {
	if x != nil {
		return x.CancelledAt
	}
	return 0
}

type GetDriverDeliveriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        DeliveryStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=delivertrack.delivery.DeliveryStatus" json:"status,omitempty"`
	Date          int64                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverDeliveriesRequest) Reset() {
	*x = GetDriverDeliveriesRequest{}
	mi := &file_delivery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverDeliveriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverDeliveriesRequest) ProtoMessage() {}

func (x *GetDriverDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverDeliveriesRequest.ProtoReflect.Descriptor instead.
func (*GetDriverDeliveriesRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{13}
}

func (x *GetDriverDeliveriesRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetDriverDeliveriesRequest) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *GetDriverDeliveriesRequest) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

type GetDriverDeliveriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*Delivery            `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverDeliveriesResponse) Reset() {
	*x = GetDriverDeliveriesResponse{}
	mi := &file_delivery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverDeliveriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverDeliveriesResponse) ProtoMessage() {}

func (x *GetDriverDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverDeliveriesResponse.ProtoReflect.Descriptor instead.
func (*GetDriverDeliveriesResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{14}
}

func (x *GetDriverDeliveriesResponse) GetDeliveries() []*Delivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *GetDriverDeliveriesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type OptimizeRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DeliveryIds   []string               `protobuf:"bytes,2,rep,name=delivery_ids,json=deliveryIds,proto3" json:"delivery_ids,omitempty"`
	StartLocation *common.Location       `protobuf:"bytes,3,opt,name=start_location,json=startLocation,proto3" json:"start_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeRouteRequest) Reset() {
	*x = OptimizeRouteRequest{}
	mi := &file_delivery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRouteRequest) ProtoMessage() {}

func (x *OptimizeRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRouteRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRouteRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{15}
}

func (x *OptimizeRouteRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *OptimizeRouteRequest) GetDeliveryIds() []string {
	if x != nil {
		return x.DeliveryIds
	}
	return nil
}

func (x *OptimizeRouteRequest) GetStartLocation() *common.Location {
	if x != nil {
		return x.StartLocation
	}
	return nil
}

type OptimizeRouteResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Route             []*RouteStop           `protobuf:"bytes,1,rep,name=route,proto3" json:"route,omitempty"`
	TotalDistance     float64                `protobuf:"fixed64,2,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`            // km
	EstimatedDuration int64                  `protobuf:"varint,3,opt,name=estimated_duration,json=estimatedDuration,proto3" json:"estimated_duration,omitempty"` // seconds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OptimizeRouteResponse) Reset() {
	*x = OptimizeRouteResponse{}
	mi := &file_delivery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRouteResponse) ProtoMessage() {}

func (x *OptimizeRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRouteResponse.ProtoReflect.Descriptor instead.
func (*OptimizeRouteResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{16}
}

func (x *OptimizeRouteResponse) GetRoute() []*RouteStop {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *OptimizeRouteResponse) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *OptimizeRouteResponse) GetEstimatedDuration() int64 {
	if x != nil {
		return x.EstimatedDuration
	}
	return 0
}

type RouteStop struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId           string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Sequence             int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Location             *common.Location       `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	EstimatedArrival     int64                  `protobuf:"varint,4,opt,name=estimated_arrival,json=estimatedArrival,proto3" json:"estimated_arrival,omitempty"`
	DistanceFromPrevious float64                `protobuf:"fixed64,5,opt,name=distance_from_previous,json=distanceFromPrevious,proto3" json:"distance_from_previous,omitempty"` // km
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RouteStop) Reset() {
	*x = RouteStop{}
	mi := &file_delivery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteStop) ProtoMessage() {}

func (x *RouteStop) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteStop.ProtoReflect.Descriptor instead.
func (*RouteStop) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{17}
}

func (x *RouteStop) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *RouteStop) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RouteStop) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *RouteStop) GetEstimatedArrival() int64 {
	if x != nil {
		return x.EstimatedArrival
	}
	return 0
}

func (x *RouteStop) GetDistanceFromPrevious() float64 {
	if x != nil {
		return x.DistanceFromPrevious
	}
	return 0
}

type ConfirmDeliveryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId       string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	SignatureData    string                 `protobuf:"bytes,2,opt,name=signature_data,json=signatureData,proto3" json:"signature_data,omitempty"` // base64 encoded signature
	PhotoData        []string               `protobuf:"bytes,3,rep,name=photo_data,json=photoData,proto3" json:"photo_data,omitempty"`             // base64 encoded photos
	RecipientName    string                 `protobuf:"bytes,4,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	DeliveryLocation *common.Location       `protobuf:"bytes,5,opt,name=delivery_location,json=deliveryLocation,proto3" json:"delivery_location,omitempty"`
	DeliveryTime     int64                  `protobuf:"varint,6,opt,name=delivery_time,json=deliveryTime,proto3" json:"delivery_time,omitempty"`
	Notes            string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfirmDeliveryRequest) Reset() {
	*x = ConfirmDeliveryRequest{}
	mi := &file_delivery_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDeliveryRequest) ProtoMessage() {}

func (x *ConfirmDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDeliveryRequest.ProtoReflect.Descriptor instead.
func (*ConfirmDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{18}
}

func (x *ConfirmDeliveryRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *ConfirmDeliveryRequest) GetSignatureData() string {
	if x != nil {
		return x.SignatureData
	}
	return ""
}

func (x *ConfirmDeliveryRequest) GetPhotoData() []string {
	if x != nil {
		return x.PhotoData
	}
	return nil
}

func (x *ConfirmDeliveryRequest) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *ConfirmDeliveryRequest) GetDeliveryLocation() *common.Location {
	if x != nil {
		return x.DeliveryLocation
	}
	return nil
}

func (x *ConfirmDeliveryRequest) GetDeliveryTime() int64 {
	if x != nil {
		return x.DeliveryTime
	}
	return 0
}

func (x *ConfirmDeliveryRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type ConfirmDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SignatureUrl  string                 `protobuf:"bytes,2,opt,name=signature_url,json=signatureUrl,proto3" json:"signature_url,omitempty"`
	PhotoUrls     []string               `protobuf:"bytes,3,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	ConfirmedAt   int64                  `protobuf:"varint,4,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDeliveryResponse) Reset() {
	*x = ConfirmDeliveryResponse{}
	mi := &file_delivery_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDeliveryResponse) ProtoMessage() {}

func (x *ConfirmDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDeliveryResponse.ProtoReflect.Descriptor instead.
func (*ConfirmDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{19}
}

func (x *ConfirmDeliveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmDeliveryResponse) GetSignatureUrl() string {
	if x != nil {
		return x.SignatureUrl
	}
	return ""
}

func (x *ConfirmDeliveryResponse) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

func (x *ConfirmDeliveryResponse) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

type PackageDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Weight            float64                `protobuf:"fixed64,1,opt,name=weight,proto3" json:"weight,omitempty"` // kg
	Length            float64                `protobuf:"fixed64,2,opt,name=length,proto3" json:"length,omitempty"` // cm
	Width             float64                `protobuf:"fixed64,3,opt,name=width,proto3" json:"width,omitempty"`   // cm
	Height            float64                `protobuf:"fixed64,4,opt,name=height,proto3" json:"height,omitempty"` // cm
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Fragile           bool                   `protobuf:"varint,6,opt,name=fragile,proto3" json:"fragile,omitempty"`
	RequiresSignature bool                   `protobuf:"varint,7,opt,name=requires_signature,json=requiresSignature,proto3" json:"requires_signature,omitempty"`
	DeclaredValue     float64                `protobuf:"fixed64,8,opt,name=declared_value,json=declaredValue,proto3" json:"declared_value,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PackageDetails) Reset() {
	*x = PackageDetails{}
	mi := &file_delivery_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageDetails) ProtoMessage() {}

func (x *PackageDetails) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageDetails.ProtoReflect.Descriptor instead.
func (*PackageDetails) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{20}
}

func (x *PackageDetails) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PackageDetails) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *PackageDetails) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PackageDetails) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PackageDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PackageDetails) GetFragile() bool {
	if x != nil {
		return x.Fragile
	}
	return false
}

func (x *PackageDetails) GetRequiresSignature() bool {
	if x != nil {
		return x.RequiresSignature
	}
	return false
}

func (x *PackageDetails) GetDeclaredValue() float64 {
	if x != nil {
		return x.DeclaredValue
	}
	return 0
}

var File_delivery_proto protoreflect.FileDescriptor

const file_delivery_proto_rawDesc = "" +
	"\n" +
	"\x0edelivery.proto\x12\x15delivertrack.delivery\x1a\fcommon.proto\"\x8d\x04\n" +
	"\x15CreateDeliveryRequest\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12F\n" +
	"\x0fpickup_location\x18\x03 \x01(\v2\x1d.delivertrack.common.LocationR\x0epickupLocation\x12J\n" +
	"\x11delivery_location\x18\x04 \x01(\v2\x1d.delivertrack.common.LocationR\x10deliveryLocation\x12)\n" +
	"\x10scheduled_pickup\x18\x05 \x01(\x03R\x0fscheduledPickup\x12-\n" +
	"\x12scheduled_delivery\x18\x06 \x01(\x03R\x11scheduledDelivery\x12C\n" +
	"\bpriority\x18\a \x01(\x0e2'.delivertrack.delivery.DeliveryPriorityR\bpriority\x12N\n" +
	"\x0fpackage_details\x18\b \x01(\v2%.delivertrack.delivery.PackageDetailsR\x0epackageDetails\x121\n" +
	"\x14special_instructions\x18\t \x01(\tR\x13specialInstructions\"\x81\x01\n" +
	"\x16CreateDeliveryResponse\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12'\n" +
	"\x0ftracking_number\x18\x02 \x01(\tR\x0etrackingNumber\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"5\n" +
	"\x12GetDeliveryRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\"R\n" +
	"\x13GetDeliveryResponse\x12;\n" +
	"\bdelivery\x18\x01 \x01(\v2\x1f.delivertrack.delivery.DeliveryR\bdelivery\"\xf6\x06\n" +
	"\bDelivery\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tR\tpackageId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\x12'\n" +
	"\x0ftracking_number\x18\x05 \x01(\tR\x0etrackingNumber\x12F\n" +
	"\x0fpickup_location\x18\x06 \x01(\v2\x1d.delivertrack.common.LocationR\x0epickupLocation\x12J\n" +
	"\x11delivery_location\x18\a \x01(\v2\x1d.delivertrack.common.LocationR\x10deliveryLocation\x12=\n" +
	"\x06status\x18\b \x01(\x0e2%.delivertrack.delivery.DeliveryStatusR\x06status\x12)\n" +
	"\x10scheduled_pickup\x18\t \x01(\x03R\x0fscheduledPickup\x12-\n" +
	"\x12scheduled_delivery\x18\n" +
	" \x01(\x03R\x11scheduledDelivery\x12#\n" +
	"\ractual_pickup\x18\v \x01(\x03R\factualPickup\x12'\n" +
	"\x0factual_delivery\x18\f \x01(\x03R\x0eactualDelivery\x12C\n" +
	"\bpriority\x18\r \x01(\x0e2'.delivertrack.delivery.DeliveryPriorityR\bpriority\x12N\n" +
	"\x0fpackage_details\x18\x0e \x01(\v2%.delivertrack.delivery.PackageDetailsR\x0epackageDetails\x121\n" +
	"\x14special_instructions\x18\x0f \x01(\tR\x13specialInstructions\x12#\n" +
	"\rsignature_url\x18\x10 \x01(\tR\fsignatureUrl\x12\x1d\n" +
	"\n" +
	"photo_urls\x18\x11 \x03(\tR\tphotoUrls\x12\x1d\n" +
	"\n" +
	"created_at\x18\x12 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\x03R\tupdatedAt\"\xce\x01\n" +
	"\x1bUpdateDeliveryStatusRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.delivertrack.delivery.DeliveryStatusR\x06status\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x129\n" +
	"\blocation\x18\x04 \x01(\v2\x1d.delivertrack.common.LocationR\blocation\"W\n" +
	"\x1cUpdateDeliveryStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\x03R\tupdatedAt\"S\n" +
	"\x13AssignDriverRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"Q\n" +
	"\x14AssignDriverResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vassigned_at\x18\x02 \x01(\x03R\n" +
	"assignedAt\"\x94\x02\n" +
	"\x15ListDeliveriesRequest\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.delivertrack.delivery.DeliveryStatusR\x06status\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12=\n" +
	"\n" +
	"time_range\x18\x04 \x01(\v2\x1e.delivertrack.common.TimeRangeR\ttimeRange\x12?\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x1f.delivertrack.common.PaginationR\n" +
	"pagination\"\xab\x01\n" +
	"\x16ListDeliveriesResponse\x12?\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2\x1f.delivertrack.delivery.DeliveryR\n" +
	"deliveries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"P\n" +
	"\x15CancelDeliveryRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"U\n" +
	"\x16CancelDeliveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fcancelled_at\x18\x02 \x01(\x03R\vcancelledAt\"\x8c\x01\n" +
	"\x1aGetDriverDeliveriesRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.delivertrack.delivery.DeliveryStatusR\x06status\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x03R\x04date\"\x7f\n" +
	"\x1bGetDriverDeliveriesResponse\x12?\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2\x1f.delivertrack.delivery.DeliveryR\n" +
	"deliveries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x9c\x01\n" +
	"\x14OptimizeRouteRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12!\n" +
	"\fdelivery_ids\x18\x02 \x03(\tR\vdeliveryIds\x12D\n" +
	"\x0estart_location\x18\x03 \x01(\v2\x1d.delivertrack.common.LocationR\rstartLocation\"\xa5\x01\n" +
	"\x15OptimizeRouteResponse\x126\n" +
	"\x05route\x18\x01 \x03(\v2 .delivertrack.delivery.RouteStopR\x05route\x12%\n" +
	"\x0etotal_distance\x18\x02 \x01(\x01R\rtotalDistance\x12-\n" +
	"\x12estimated_duration\x18\x03 \x01(\x03R\x11estimatedDuration\"\xe6\x01\n" +
	"\tRouteStop\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\x129\n" +
	"\blocation\x18\x03 \x01(\v2\x1d.delivertrack.common.LocationR\blocation\x12+\n" +
	"\x11estimated_arrival\x18\x04 \x01(\x03R\x10estimatedArrival\x124\n" +
	"\x16distance_from_previous\x18\x05 \x01(\x01R\x14distanceFromPrevious\"\xad\x02\n" +
	"\x16ConfirmDeliveryRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12%\n" +
	"\x0esignature_data\x18\x02 \x01(\tR\rsignatureData\x12\x1d\n" +
	"\n" +
	"photo_data\x18\x03 \x03(\tR\tphotoData\x12%\n" +
	"\x0erecipient_name\x18\x04 \x01(\tR\rrecipientName\x12J\n" +
	"\x11delivery_location\x18\x05 \x01(\v2\x1d.delivertrack.common.LocationR\x10deliveryLocation\x12#\n" +
	"\rdelivery_time\x18\x06 \x01(\x03R\fdeliveryTime\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"\x9a\x01\n" +
	"\x17ConfirmDeliveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rsignature_url\x18\x02 \x01(\tR\fsignatureUrl\x12\x1d\n" +
	"\n" +
	"photo_urls\x18\x03 \x03(\tR\tphotoUrls\x12!\n" +
	"\fconfirmed_at\x18\x04 \x01(\x03R\vconfirmedAt\"\x80\x02\n" +
	"\x0ePackageDetails\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x01R\x06weight\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x01R\x06height\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\afragile\x18\x06 \x01(\bR\afragile\x12-\n" +
	"\x12requires_signature\x18\a \x01(\bR\x11requiresSignature\x12%\n" +
	"\x0edeclared_value\x18\b \x01(\x01R\rdeclaredValue*\xc9\x02\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DELIVERY_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18DELIVERY_STATUS_ASSIGNED\x10\x02\x12\x1d\n" +
	"\x19DELIVERY_STATUS_PICKED_UP\x10\x03\x12\x1e\n" +
	"\x1aDELIVERY_STATUS_IN_TRANSIT\x10\x04\x12$\n" +
	" DELIVERY_STATUS_OUT_FOR_DELIVERY\x10\x05\x12\x1d\n" +
	"\x19DELIVERY_STATUS_DELIVERED\x10\x06\x12\x1a\n" +
	"\x16DELIVERY_STATUS_FAILED\x10\a\x12\x1d\n" +
	"\x19DELIVERY_STATUS_CANCELLED\x10\b\x12\x1c\n" +
	"\x18DELIVERY_STATUS_RETURNED\x10\t*\x85\x01\n" +
	"\x10DeliveryPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PRIORITY_STANDARD\x10\x01\x12\x14\n" +
	"\x10PRIORITY_EXPRESS\x10\x02\x12\x15\n" +
	"\x11PRIORITY_SAME_DAY\x10\x03\x12\x13\n" +
	"\x0fPRIORITY_URGENT\x10\x042\x8a\b\n" +
	"\x0fDeliveryService\x12m\n" +
	"\x0eCreateDelivery\x12,.delivertrack.delivery.CreateDeliveryRequest\x1a-.delivertrack.delivery.CreateDeliveryResponse\x12d\n" +
	"\vGetDelivery\x12).delivertrack.delivery.GetDeliveryRequest\x1a*.delivertrack.delivery.GetDeliveryResponse\x12\x7f\n" +
	"\x14UpdateDeliveryStatus\x122.delivertrack.delivery.UpdateDeliveryStatusRequest\x1a3.delivertrack.delivery.UpdateDeliveryStatusResponse\x12g\n" +
	"\fAssignDriver\x12*.delivertrack.delivery.AssignDriverRequest\x1a+.delivertrack.delivery.AssignDriverResponse\x12m\n" +
	"\x0eListDeliveries\x12,.delivertrack.delivery.ListDeliveriesRequest\x1a-.delivertrack.delivery.ListDeliveriesResponse\x12m\n" +
	"\x0eCancelDelivery\x12,.delivertrack.delivery.CancelDeliveryRequest\x1a-.delivertrack.delivery.CancelDeliveryResponse\x12|\n" +
	"\x13GetDriverDeliveries\x121.delivertrack.delivery.GetDriverDeliveriesRequest\x1a2.delivertrack.delivery.GetDriverDeliveriesResponse\x12j\n" +
	"\rOptimizeRoute\x12+.delivertrack.delivery.OptimizeRouteRequest\x1a,.delivertrack.delivery.OptimizeRouteResponse\x12p\n" +
	"\x0fConfirmDelivery\x12-.delivertrack.delivery.ConfirmDeliveryRequest\x1a..delivertrack.delivery.ConfirmDeliveryResponseB5Z3github.com/Keneke-Einar/delivertrack/proto/deliveryb\x06proto3"

var (
	file_delivery_proto_rawDescOnce sync.Once
	file_delivery_proto_rawDescData []byte
)

func file_delivery_proto_rawDescGZIP() []byte {
	file_delivery_proto_rawDescOnce.Do(func() {
		file_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_proto_rawDesc), len(file_delivery_proto_rawDesc)))
	})
	return file_delivery_proto_rawDescData
}

var file_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_delivery_proto_goTypes = []any{
	(DeliveryStatus)(0),                  // 0: delivertrack.delivery.DeliveryStatus
	(DeliveryPriority)(0),                // 1: delivertrack.delivery.DeliveryPriority
	(*CreateDeliveryRequest)(nil),        // 2: delivertrack.delivery.CreateDeliveryRequest
	(*CreateDeliveryResponse)(nil),       // 3: delivertrack.delivery.CreateDeliveryResponse
	(*GetDeliveryRequest)(nil),           // 4: delivertrack.delivery.GetDeliveryRequest
	(*GetDeliveryResponse)(nil),          // 5: delivertrack.delivery.GetDeliveryResponse
	(*Delivery)(nil),                     // 6: delivertrack.delivery.Delivery
	(*UpdateDeliveryStatusRequest)(nil),  // 7: delivertrack.delivery.UpdateDeliveryStatusRequest
	(*UpdateDeliveryStatusResponse)(nil), // 8: delivertrack.delivery.UpdateDeliveryStatusResponse
	(*AssignDriverRequest)(nil),          // 9: delivertrack.delivery.AssignDriverRequest
	(*AssignDriverResponse)(nil),         // 10: delivertrack.delivery.AssignDriverResponse
	(*ListDeliveriesRequest)(nil),        // 11: delivertrack.delivery.ListDeliveriesRequest
	(*ListDeliveriesResponse)(nil),       // 12: delivertrack.delivery.ListDeliveriesResponse
	(*CancelDeliveryRequest)(nil),        // 13: delivertrack.delivery.CancelDeliveryRequest
	(*CancelDeliveryResponse)(nil),       // 14: delivertrack.delivery.CancelDeliveryResponse
	(*GetDriverDeliveriesRequest)(nil),   // 15: delivertrack.delivery.GetDriverDeliveriesRequest
	(*GetDriverDeliveriesResponse)(nil),  // 16: delivertrack.delivery.GetDriverDeliveriesResponse
	(*OptimizeRouteRequest)(nil),         // 17: delivertrack.delivery.OptimizeRouteRequest
	(*OptimizeRouteResponse)(nil),        // 18: delivertrack.delivery.OptimizeRouteResponse
	(*RouteStop)(nil),                    // 19: delivertrack.delivery.RouteStop
	(*ConfirmDeliveryRequest)(nil),       // 20: delivertrack.delivery.ConfirmDeliveryRequest
	(*ConfirmDeliveryResponse)(nil),      // 21: delivertrack.delivery.ConfirmDeliveryResponse
	(*PackageDetails)(nil),               // 22: delivertrack.delivery.PackageDetails
	(*common.Location)(nil),              // 23: delivertrack.common.Location
	(*common.TimeRange)(nil),             // 24: delivertrack.common.TimeRange
	(*common.Pagination)(nil),            // 25: delivertrack.common.Pagination
}
var file_delivery_proto_depIdxs = []int32{
	23, // 0: delivertrack.delivery.CreateDeliveryRequest.pickup_location:type_name -> delivertrack.common.Location
	23, // 1: delivertrack.delivery.CreateDeliveryRequest.delivery_location:type_name -> delivertrack.common.Location
	1,  // 2: delivertrack.delivery.CreateDeliveryRequest.priority:type_name -> delivertrack.delivery.DeliveryPriority
	22, // 3: delivertrack.delivery.CreateDeliveryRequest.package_details:type_name -> delivertrack.delivery.PackageDetails
	6,  // 4: delivertrack.delivery.GetDeliveryResponse.delivery:type_name -> delivertrack.delivery.Delivery
	23, // 5: delivertrack.delivery.Delivery.pickup_location:type_name -> delivertrack.common.Location
	23, // 6: delivertrack.delivery.Delivery.delivery_location:type_name -> delivertrack.common.Location
	0,  // 7: delivertrack.delivery.Delivery.status:type_name -> delivertrack.delivery.DeliveryStatus
	1,  // 8: delivertrack.delivery.Delivery.priority:type_name -> delivertrack.delivery.DeliveryPriority
	22, // 9: delivertrack.delivery.Delivery.package_details:type_name -> delivertrack.delivery.PackageDetails
	0,  // 10: delivertrack.delivery.UpdateDeliveryStatusRequest.status:type_name -> delivertrack.delivery.DeliveryStatus
	23, // 11: delivertrack.delivery.UpdateDeliveryStatusRequest.location:type_name -> delivertrack.common.Location
	0,  // 12: delivertrack.delivery.ListDeliveriesRequest.status:type_name -> delivertrack.delivery.DeliveryStatus
	24, // 13: delivertrack.delivery.ListDeliveriesRequest.time_range:type_name -> delivertrack.common.TimeRange
	25, // 14: delivertrack.delivery.ListDeliveriesRequest.pagination:type_name -> delivertrack.common.Pagination
	6,  // 15: delivertrack.delivery.ListDeliveriesResponse.deliveries:type_name -> delivertrack.delivery.Delivery
	0,  // 16: delivertrack.delivery.GetDriverDeliveriesRequest.status:type_name -> delivertrack.delivery.DeliveryStatus
	6,  // 17: delivertrack.delivery.GetDriverDeliveriesResponse.deliveries:type_name -> delivertrack.delivery.Delivery
	23, // 18: delivertrack.delivery.OptimizeRouteRequest.start_location:type_name -> delivertrack.common.Location
	19, // 19: delivertrack.delivery.OptimizeRouteResponse.route:type_name -> delivertrack.delivery.RouteStop
	23, // 20: delivertrack.delivery.RouteStop.location:type_name -> delivertrack.common.Location
	23, // 21: delivertrack.delivery.ConfirmDeliveryRequest.delivery_location:type_name -> delivertrack.common.Location
	2,  // 22: delivertrack.delivery.DeliveryService.CreateDelivery:input_type -> delivertrack.delivery.CreateDeliveryRequest
	4,  // 23: delivertrack.delivery.DeliveryService.GetDelivery:input_type -> delivertrack.delivery.GetDeliveryRequest
	7,  // 24: delivertrack.delivery.DeliveryService.UpdateDeliveryStatus:input_type -> delivertrack.delivery.UpdateDeliveryStatusRequest
	9,  // 25: delivertrack.delivery.DeliveryService.AssignDriver:input_type -> delivertrack.delivery.AssignDriverRequest
	11, // 26: delivertrack.delivery.DeliveryService.ListDeliveries:input_type -> delivertrack.delivery.ListDeliveriesRequest
	13, // 27: delivertrack.delivery.DeliveryService.CancelDelivery:input_type -> delivertrack.delivery.CancelDeliveryRequest
	15, // 28: delivertrack.delivery.DeliveryService.GetDriverDeliveries:input_type -> delivertrack.delivery.GetDriverDeliveriesRequest
	17, // 29: delivertrack.delivery.DeliveryService.OptimizeRoute:input_type -> delivertrack.delivery.OptimizeRouteRequest
	20, // 30: delivertrack.delivery.DeliveryService.ConfirmDelivery:input_type -> delivertrack.delivery.ConfirmDeliveryRequest
	3,  // 31: delivertrack.delivery.DeliveryService.CreateDelivery:output_type -> delivertrack.delivery.CreateDeliveryResponse
	5,  // 32: delivertrack.delivery.DeliveryService.GetDelivery:output_type -> delivertrack.delivery.GetDeliveryResponse
	8,  // 33: delivertrack.delivery.DeliveryService.UpdateDeliveryStatus:output_type -> delivertrack.delivery.UpdateDeliveryStatusResponse
	10, // 34: delivertrack.delivery.DeliveryService.AssignDriver:output_type -> delivertrack.delivery.AssignDriverResponse
	12, // 35: delivertrack.delivery.DeliveryService.ListDeliveries:output_type -> delivertrack.delivery.ListDeliveriesResponse
	14, // 36: delivertrack.delivery.DeliveryService.CancelDelivery:output_type -> delivertrack.delivery.CancelDeliveryResponse
	16, // 37: delivertrack.delivery.DeliveryService.GetDriverDeliveries:output_type -> delivertrack.delivery.GetDriverDeliveriesResponse
	18, // 38: delivertrack.delivery.DeliveryService.OptimizeRoute:output_type -> delivertrack.delivery.OptimizeRouteResponse
	21, // 39: delivertrack.delivery.DeliveryService.ConfirmDelivery:output_type -> delivertrack.delivery.ConfirmDeliveryResponse
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_delivery_proto_init() }
func file_delivery_proto_init() {
	if File_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_proto_rawDesc), len(file_delivery_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_proto_goTypes,
		DependencyIndexes: file_delivery_proto_depIdxs,
		EnumInfos:         file_delivery_proto_enumTypes,
		MessageInfos:      file_delivery_proto_msgTypes,
	}.Build()
	File_delivery_proto = out.File
	file_delivery_proto_goTypes = nil
	file_delivery_proto_depIdxs = nil
}
